create table public.matches (
  id bigint generated by default as identity not null,
  player1_id integer not null,
  player2_id integer not null,
  winner_id integer not null,
  is_fake_data boolean not null default false,
  player1_score smallint not null,
  player2_score smallint null,
  constraint matches_pkey primary key (id),
  constraint matches_player1id_fkey foreign KEY (player1_id) references players (id) on update CASCADE on delete CASCADE,
  constraint matches_player2id_fkey foreign KEY (player2_id) references players (id) on update CASCADE on delete CASCADE,
  constraint matches_winnerid_fkey foreign KEY (winner_id) references players (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists matches_id_idx on public.matches using btree (id) TABLESPACE pg_default;

create index IF not exists matches_player2_id_idx on public.matches using btree (player2_id) TABLESPACE pg_default;

create index IF not exists matches_winner_id_idx on public.matches using btree (winner_id) TABLESPACE pg_default;




create table public.matches (
  id bigint generated by default as identity not null,
  player1_id integer not null,
  player2_id integer not null,
  winner_id integer not null,
  is_fake_data boolean not null default false,
  player1_score smallint not null,
  player2_score smallint null,
  constraint matches_pkey primary key (id),
  constraint matches_player1id_fkey foreign KEY (player1_id) references players (id) on update CASCADE on delete CASCADE,
  constraint matches_player2id_fkey foreign KEY (player2_id) references players (id) on update CASCADE on delete CASCADE,
  constraint matches_winnerid_fkey foreign KEY (winner_id) references players (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists matches_id_idx on public.matches using btree (id) TABLESPACE pg_default;

create index IF not exists matches_player2_id_idx on public.matches using btree (player2_id) TABLESPACE pg_default;

create index IF not exists matches_winner_id_idx on public.matches using btree (winner_id) TABLESPACE pg_default;