--   CRITICAL: This script is generated by generate-seed.cjs do not modify this script directly.



-- Seed data generated from sampleData.csv
-- Total matches: 459
-- Total events: 5
-- Historical data: archived seasons (IDs 1-5)
-- New active season: ID 0

DO $$
BEGIN
  DROP TABLE IF EXISTS seeddata;
  CREATE TEMP TABLE seeddata(
    row_index INT,
    player1 varchar(128),
    player2 varchar(128),
    player1score INT,
    player2score INT,
    event varchar(128),
    winner varchar(128),
    season_id INT
  );

  INSERT INTO seeddata (row_index, player1, player2, player1score, player2score, event, winner, season_id) 
  VALUES
    (1, 'MonkeyKing','Fon',5,2,'Season 1','MonkeyKing', 1),
    (2, 'dopppa','Terachi',5,2,'Season 1','dopppa', 1),
    (3, 'Spirit410','Domitto',10,6,'Season 1','Spirit410', 1),
    (4, 'Prizvel','Cpt-GI',5,3,'Season 1','Prizvel', 1),
    (5, 'Mozarus','Spear',5,3,'Season 1','Mozarus', 1),
    (6, 'Stray','SHARK',5,0,'Season 1','Stray', 1),
    (7, 'Ol[d]cadan','Polosaty',5,1,'Season 1','Ol[d]cadan', 1),
    (8, 'Hamidumi','Carnhulio',5,3,'Season 1','Hamidumi', 1),
    (9, 'D3xus','Habaduba',10,3,'Season 1','D3xus', 1),
    (10, 'MPhantasm','Vegasvat',5,1,'Season 1','MPhantasm', 1),
    (11, 'Taokaka Meow','Jc_near',5,3,'Season 1','Taokaka Meow', 1),
    (12, 'Baddy','Valhanya',5,4,'Season 1','Baddy', 1),
    (13, 'Ganondeurf','Yin',10,7,'Season 1','Ganondeurf', 1),
    (14, 'SHARK','K.D.C.',5,1,'Season 1','SHARK', 1),
    (15, 'Stray','TapiocaKing',5,1,'Season 1','Stray', 1),
    (16, 'VileMuffin','Prizvel',5,0,'Season 1','VileMuffin', 1),
    (17, 'dopppa','Hamidumi',5,2,'Season 1','dopppa', 1),
    (18, 'Rufus','Aelz',5,3,'Season 1','Rufus', 1),
    (19, 'Cpt-GI','Polosaty',5,1,'Season 1','Cpt-GI', 1),
    (20, 'Volty','TangAce',5,0,'Season 1','Volty', 1),
    (21, 'Fotten','Zephyrion',5,0,'Season 1','Fotten', 1),
    (22, 'Guilu','Sett',5,1,'Season 1','Guilu', 1),
    (23, 'Ssylus','Andyroo',10,3,'Season 1','Ssylus', 1),
    (24, 'Azizure','Taz',5,4,'Season 1','Azizure', 1),
    (25, 'Graveryl','Momotehk',5,1,'Season 1','Graveryl', 1),
    (26, 'Sett','Doktai',5,4,'Season 1','Sett', 1),
    (27, 'Sams','Habaduba',10,6,'Season 1','Sams', 1),
    (28, 'PanPan','Yuusha42',5,4,'Season 1','PanPan', 1),
    (29, 'VileMuffin','Taokaka Meow',5,4,'Season 1','VileMuffin', 1),
    (30, 'Ceiwen','Sekirei',5,3,'Season 1','Ceiwen', 1),
    (31, 'Domitto','Neon',10,8,'Season 1','Domitto', 1),
    (32, 'Spear','Hamidumi',5,0,'Season 1','Spear', 1),
    (33, 'Zephyrion','SHARK',5,2,'Season 1','Zephyrion', 1),
    (34, 'Volty','Ennvill',5,4,'Season 1','Volty', 1),
    (35, 'Vegasvat','Ol[d]cadan',5,3,'Season 1','Vegasvat', 1),
    (36, 'Guilu','MonkeyKing',5,0,'Season 1','Guilu', 1),
    (37, 'Valhanya','Carnhulio',5,0,'Season 1','Valhanya', 1),
    (38, 'Ganondeurf','Spirit410',5,2,'Season 1','Ganondeurf', 1),
    (39, 'Carriacou','TapiocaKing',5,0,'Season 1','Carriacou', 1),
    (40, 'Aby','Stray',5,3,'Season 1','Aby', 1),
    (41, 'Baddy','Mozarus',5,1,'Season 1','Baddy', 1),
    (42, 'Aarpia','DarthSeppius',10,4,'Season 1','Aarpia', 1),
    (43, 'SHARK','Tadlos',5,4,'Season 1','SHARK', 1),
    (44, 'MonkeyKing','Terachi',5,1,'Season 1','MonkeyKing', 1),
    (45, 'Azizure','dopppa',5,1,'Season 1','Azizure', 1),
    (46, 'ZappySoyou','Spirit410',5,3,'Season 1','ZappySoyou', 1),
    (47, 'Jazair','Prizvel',5,0,'Season 1','Jazair', 1),
    (48, 'Carriacou','Stray',5,4,'Season 1','Carriacou', 1),
    (49, 'Carnhulio','Vegasvat',5,4,'Season 1','Carnhulio', 1),
    (50, 'D3xus','Aelz',10,1,'Season 1','D3xus', 1),
    (51, 'Zephyrion','PanPan',5,0,'Season 1','Zephyrion', 1),
    (52, 'Taz','Sekirei',5,2,'Season 1','Taz', 1),
    (53, 'Nickvold','TapiocaKing',5,3,'Season 1','Nickvold', 1),
    (54, 'Ventras','Hamidumi',5,0,'Season 1','Ventras', 1),
    (55, 'Sett','VileMuffin',5,2,'Season 1','Sett', 1),
    (56, 'D3xus','Ssylus',5,3,'Season 1','D3xus', 1),
    (57, 'Doktai','Aby',5,1,'Season 1','Doktai', 1),
    (58, 'Volty','Ryuki',5,1,'Season 1','Volty', 1),
    (59, 'Algernon','Taokaka Meow',5,3,'Season 1','Algernon', 1),
    (60, 'Domitto','DarthSeppius',10,9,'Season 1','Domitto', 1),
    (61, 'Blade of Flame','LozKias',5,1,'Season 1','Blade of Flame', 1),
    (62, 'Fanlee Jr','Ceiwen',5,3,'Season 1','Fanlee Jr', 1),
    (63, 'Baddy','Zollith',5,3,'Season 1','Baddy', 1),
    (64, 'Aarpia','HolyCarp',5,0,'Season 1','Aarpia', 1),
    (65, 'Jazair','Doktai',5,0,'Season 1','Jazair', 1),
    (66, 'Stray','Nickvold',5,0,'Season 1','Stray', 1),
    (67, 'MonkeyKing','Graveryl',5,3,'Season 1','MonkeyKing', 1),
    (68, 'Algernon','dopppa',5,2,'Season 1','Algernon', 1),
    (69, 'polosaty','Ennvill',5,3,'Season 1','polosaty', 1),
    (70, 'Yaj-Ly','Ryuki',5,1,'Season 1','Yaj-Ly', 1),
    (71, 'Zanaken','Volty',5,1,'Season 1','Zanaken', 1),
    (72, 'Rufus','DarthSeppius',10,1,'Season 1','Rufus', 1),
    (73, 'Prizvel','Vegasvat',5,1,'Season 1','Prizvel', 1),
    (74, 'VileMuffin','Ventras',5,4,'Season 1','VileMuffin', 1),
    (75, 'LozKias','Taz',5,2,'Season 1','LozKias', 1),
    (76, 'Ceiwen','Azizure',5,1,'Season 1','Ceiwen', 1),
    (77, 'PanPan','Momotehk',5,4,'Season 1','PanPan', 1),
    (78, 'Hazu','Zollith',5,0,'Season 1','Hazu', 1),
    (79, 'Zaydan','Taokaka Meow',5,4,'Season 1','Zaydan', 1),
    (80, 'Neon','Habaduba',10,8,'Season 1','Neon', 1),
    (81, 'Sett','Valhanya',5,2,'Season 1','Sett', 1),
    (82, 'Baddy','Guilu',10,4,'Season 1','Baddy', 1),
    (83, 'Aelz','ZappySoyou',5,1,'Season 1','Aelz', 1),
    (84, 'Ssylus','Domitto',5,3,'Season 1','Ssylus', 1),
    (85, 'D3xus','Ganondeurf',10,5,'Season 1','D3xus', 1),
    (86, 'SHARK','TapiocaKing',5,2,'Season 2','SHARK', 2),
    (87, 'HawkOfGP','Carriacou',5,1,'Season 2','HawkOfGP', 2),
    (88, 'Danurai','Aby',5,4,'Season 2','Danurai', 2),
    (89, 'Yin','Andyroo',10,7,'Season 2','Yin', 2),
    (90, 'Ventras','Taokaka Meow',5,0,'Season 2','Ventras', 2),
    (91, 'Yaj-Ly','PanPan',5,4,'Season 2','Yaj-Ly', 2),
    (92, 'Graveryl','Rosa',5,1,'Season 2','Graveryl', 2),
    (93, 'DarthSeppius','Baddy',10,9,'Season 2','DarthSeppius', 2),
    (94, 'Aby','The Arpeggiator',5,3,'Season 2','Aby', 2),
    (95, 'Blade of Flame','Jazair',5,3,'Season 2','Blade of Flame', 2),
    (96, 'Sett','Habaduba',5,3,'Season 2','Sett', 2),
    (97, 'D3xus','Aarpia',10,7,'Season 2','D3xus', 2),
    (98, 'Stray','polosaty',5,4,'Season 2','Stray', 2),
    (99, 'Volty','Carriacou',5,3,'Season 2','Volty', 2),
    (100, 'Mozarus','Hazu',5,3,'Season 2','Mozarus', 2),
    (101, 'Aelz','Domitto',10,5,'Season 2','Aelz', 2),
    (102, 'Ryuki','Tadlos',5,3,'Season 2','Ryuki', 2),
    (103, 'Polosaty','TapiocaKing',5,0,'Season 2','Polosaty', 2),
    (104, 'Ventras','Volty',5,0,'Season 2','Ventras', 2),
    (105, 'VileMuffin','Habaduba',5,1,'Season 2','VileMuffin', 2),
    (106, 'Momotehk','The Arpeggiator',5,0,'Season 2','Momotehk', 2),
    (107, 'Algernon','Ceiwen',5,2,'Season 2','Algernon', 2),
    (108, 'Doktai','Graveryl',5,3,'Season 2','Doktai', 2),
    (109, 'Domitto','ZER0',5,4,'Season 2','Domitto', 2),
    (110, 'Ennvill','Prizvel',5,4,'Season 2','Ennvill', 2),
    (111, 'Carnhulio','dopppa',5,3,'Season 2','Carnhulio', 2),
    (112, 'MonkeyKing','Mozarus',5,2,'Season 2','MonkeyKing', 2),
    (113, 'Neon','ZappySoyou',5,2,'Season 2','Neon', 2),
    (114, 'Lyonide','Dzing',5,4,'Season 2','Lyonide', 2),
    (115, 'Aby','Zephyrion',5,3,'Season 2','Aby', 2),
    (116, 'Sett','Baddy',10,8,'Season 2','Sett', 2),
    (117, 'PanPan','Fergus',5,2,'Season 2','PanPan', 2),
    (118, 'Zephyrion','Volty',5,2,'Season 2','Zephyrion', 2),
    (119, 'Ventras','Mozarus',5,1,'Season 2','Ventras', 2),
    (120, 'Baddy','VileMuffin',5,4,'Season 2','Baddy', 2),
    (121, 'Ol[d]cadan','Nickvold',5,0,'Season 2','Ol[d]cadan', 2),
    (122, 'Prizvel','Kreozot',5,3,'Season 2','Prizvel', 2),
    (123, 'Polosaty','Sonder',5,1,'Season 2','Polosaty', 2),
    (124, 'Algernon','MonkeyKing',5,1,'Season 2','Algernon', 2),
    (125, 'Habaduba','Blade of Flame',5,0,'Season 2','Habaduba', 2),
    (126, 'Stray','Sonder',5,3,'Season 2','Stray', 2),
    (127, 'Lyonide','Aby',5,3,'Season 2','Lyonide', 2),
    (128, 'Aelz','Ssylus',10,9,'Season 2','Aelz', 2),
    (129, 'ZappySoyou','Sett',5,2,'Season 2','ZappySoyou', 2),
    (130, 'Aarpia','ZER0',5,0,'Season 2','Aarpia', 2),
    (131, 'Aelz','D3xus',10,5,'Season 2','Aelz', 2),
    (133, 'MonkeyKing','Polosaty',5,1,'Season 2','MonkeyKing', 2),
    (134, 'Zephyrion','Stray',5,2,'Season 2','Zephyrion', 2),
    (135, 'Lyonide','Taz',5,3,'Season 2','Lyonide', 2),
    (136, 'Baddy','Algernon',10,8,'Season 2','Baddy', 2),
    (137, 'Tadlos','Nickvold',5,0,'Season 2','Tadlos', 2),
    (138, 'LozKias','Doktai',5,4,'Season 2','LozKias', 2),
    (139, 'PanPan','Volty',5,4,'Season 2','PanPan', 2),
    (140, 'Habaduba','Ventras',5,4,'Season 2','Habaduba', 2),
    (141, 'Sonder','Pikapi',5,0,'Season 2','Sonder', 2),
    (142, 'Polosaty','Finzy',5,2,'Season 2','Polosaty', 2),
    (143, 'Habaduba','LozKias',5,3,'Season 2','Habaduba', 2),
    (144, 'D3xus','Domitto',5,1,'Season 2','D3xus', 2),
    (145, 'ETS','Nickvold',5,1,'Season 2','ETS', 2),
    (146, 'PanPan','Sekirei',5,2,'Season 2','PanPan', 2),
    (147, 'VileMuffin','MonkeyKing',5,3,'Season 2','VileMuffin', 2),
    (148, 'Andyroo','Baddy',10,8,'Season 2','Andyroo', 2),
    (149, 'Dzing','Vincent',5,4,'Season 2','Dzing', 2),
    (150, 'Graveryl','Zephyrion',5,1,'Season 2','Graveryl', 2),
    (151, 'Ventras','Lyonide',5,4,'Season 2','Ventras', 2),
    (152, 'Guilu','Zanaken',5,3,'Season 2','Guilu', 2),
    (153, 'Sonder','Ryuki',5,0,'Season 2','Sonder', 2),
    (154, 'Darxy','Hazu',5,0,'Season 2','Darxy', 2),
    (155, 'LozKias','Algernon',5,4,'Season 2','LozKias', 2),
    (156, 'HolyCarp','Sett',5,1,'Season 2','HolyCarp', 2),
    (157, 'Finzy','Pikapi',5,4,'Season 2','Finzy', 2),
    (158, 'ETS','Polosaty',5,2,'Season 2','ETS', 2),
    (159, 'Lyonide','Graveryl',5,4,'Season 2','Lyonide', 2),
    (160, 'VileMuffin','Ventras',5,4,'Season 2','VileMuffin', 2),
    (161, 'Tadlos','SiloZen',5,0,'Season 2','Tadlos', 2),
    (162, 'Doktai','PanPan',5,1,'Season 2','Doktai', 2),
    (163, 'Zollith','Aby',5,0,'Season 2','Zollith', 2),
    (164, 'Baddy','Habaduba',10,3,'Season 2','Baddy', 2),
    (165, 'Valhanya','Jazair',5,0,'Season 2','Valhanya', 2),
    (166, 'Sonder','Finzy',5,2,'Season 2','Sonder', 2),
    (167, 'Habaduba','Lyonide',5,3,'Season 2','Habaduba', 2),
    (168, 'Aarpia','D3xus',10,5,'Season 2','Aarpia', 2),
    (169, 'Pikapi','Ryuki',5,4,'Season 2','Pikapi', 2),
    (170, 'Graveryl','Unicorn',5,1,'Season 2','Graveryl', 2),
    (171, 'Tadlos','TapiocaKing',5,2,'Season 2','Tadlos', 2),
    (172, 'Myloes','Sett',5,3,'Season 2','Myloes', 2),
    (173, 'Tadlos','Momotehk',5,0,'Season 2','Tadlos', 2),
    (174, 'Rosa','Zaydan',5,0,'Season 2','Rosa', 2),
    (175, 'WorldBranstar','Aby',5,2,'Season 2','WorldBranstar', 2),
    (176, 'Ceiwen','VileMuffin',5,1,'Season 2','Ceiwen', 2),
    (177, 'The Arpeggiator','Nickvold',5,0,'Season 2','The Arpeggiator', 2),
    (178, 'Stray','ETS',5,4,'Season 2','Stray', 2),
    (179, 'Hazu','Dzing',5,1,'Season 2','Hazu', 2),
    (180, 'Sams','Baddy',10,5,'Season 2','Sams', 2),
    (181, 'Polosaty','Vincent',5,4,'Season 2','Polosaty', 2),
    (182, 'Carriacou','Ol[d]cadan',5,3,'Season 2','Carriacou', 2),
    (183, 'Zanaken','MonkeyKing',5,2,'Season 2','Zanaken', 2),
    (184, 'Domitto','Andyroo',10,3,'Season 2','Domitto', 2),
    (185, 'LozKias','Lyonide',5,4,'Season 2','LozKias', 2),
    (186, 'Habaduba','VileMuffin',5,3,'Season 2','Habaduba', 2),
    (187, 'Baddy','Sett',10,2,'Season 2','Baddy', 2),
    (188, 'D3xus','Aelz',10,6,'Season 2','D3xus', 2),
    (189, 'Zephyrion','Kellerak',5,3,'Season 3','Zephyrion', 3),
    (190, 'WorldBranstar','Kusoge',5,0,'Season 3','WorldBranstar', 3),
    (191, 'Unicorn','Momotehk',5,3,'Season 3','Unicorn', 3),
    (192, 'D3xus','Ssylus',10,2,'Season 3','D3xus', 3),
    (193, 'Yaj-Ly','Tadlos',5,3,'Season 3','Yaj-Ly', 3),
    (194, 'Fotten','LozKias',5,1,'Season 3','Fotten', 3),
    (195, 'Jazair','Lyonide',5,4,'Season 3','Jazair', 3),
    (196, 'Ol[d]cadan','Vincent',5,2,'Season 3','Ol[d]cadan', 3),
    (197, 'Vegasvat','Miha',5,1,'Season 3','Vegasvat', 3),
    (198, 'MPhantasm','MonkeyKing',5,4,'Season 3','MPhantasm', 3),
    (199, 'Rufus','Spirit410',5,1,'Season 3','Rufus', 3),
    (200, 'Stray','Taokaka Meow',5,4,'Season 3','Stray', 3),
    (201, 'Darxy','Zollith',5,1,'Season 3','Darxy', 3),
    (202, 'Yin','DarthSeppius',10,3,'Season 3','Yin', 3),
    (203, 'The Arpeggiator','Kellerak',5,4,'Season 3','The Arpeggiator', 3),
    (204, 'Hazu','Afflatus Misery',5,2,'Season 3','Hazu', 3),
    (205, 'Fotten','Lyonide',5,1,'Season 3','Fotten', 3),
    (206, 'Ganondeurf','Domitto',10,0,'Season 3','Ganondeurf', 3),
    (207, 'Petronixman','Miha',5,3,'Season 3','Petronixman', 3),
    (208, 'Vincent','Momotehk',5,1,'Season 3','Vincent', 3),
    (209, 'Aelz','Rufus',10,6,'Season 3','Aelz', 3),
    (210, 'Drunky','Kusoge',5,3,'Season 3','Drunky', 3),
    (211, 'Taokaka Meow','Sekirei',5,1,'Season 3','Taokaka Meow', 3),
    (212, 'LozKias','VileMuffin',5,1,'Season 3','LozKias', 3),
    (213, 'Baddy','Myloes',5,1,'Season 3','Baddy', 3),
    (214, 'Yaj-Ly','Greywall',5,3,'Season 3','Yaj-Ly', 3),
    (215, 'Zephyrion','Polosaty',5,1,'Season 3','Zephyrion', 3),
    (216, 'WorldBranstar','Lyonide',5,2,'Season 3','WorldBranstar', 3),
    (217, 'Raziel','Ganondeurf',5,1,'Season 3','Raziel', 3),
    (218, 'Taokaka Meow','Iona Rose',5,1,'Season 3','Taokaka Meow', 3),
    (219, 'Kellerak','Unicorn',10,0,'Season 3','Kellerak', 3),
    (220, 'Habaduba','Fotten',10,6,'Season 3','Habaduba', 3),
    (221, 'Afflatus Misery','Tadlos',5,1,'Season 3','Afflatus Misery', 3),
    (222, 'Ventras','Ceiwen',5,4,'Season 3','Ventras', 3),
    (223, 'Ssylus','Baddy',5,1,'Season 3','Ssylus', 3),
    (224, 'Kusoge','Horken',5,2,'Season 3','Kusoge', 3),
    (225, 'Zephyrion','Yaj-Ly',5,2,'Season 3','Zephyrion', 3),
    (226, 'WorldBranstar','Fotten',5,1,'Season 3','WorldBranstar', 3),
    (227, 'Greywall','TapiocaKing',5,1,'Season 3','Greywall', 3),
    (228, 'Stray','Vincent',5,3,'Season 3','Stray', 3),
    (229, 'Taokaka Meow','Hazu',5,4,'Season 3','Taokaka Meow', 3),
    (230, 'MonkeyKing','Algernon',5,3,'Season 3','MonkeyKing', 3),
    (231, 'LozKias','Zanaken',5,0,'Season 3','LozKias', 3),
    (232, 'Carriacou','Horken',5,3,'Season 3','Carriacou', 3),
    (233, 'WorldBranstar','LozKias',5,2,'Season 3','WorldBranstar', 3),
    (234, 'Valhanya','VileMuffin',5,4,'Season 3','Valhanya', 3),
    (235, 'Sams','Ganondeurf',10,6,'Season 3','Sams', 3),
    (236, 'Tadlos','Greywall',5,4,'Season 3','Tadlos', 3),
    (237, 'Stray','Yaj-Ly',5,0,'Season 3','Stray', 3),
    (238, 'Zollith','Aby',5,4,'Season 3','Zollith', 3),
    (239, 'Darxy','Taokaka Meow',5,2,'Season 3','Darxy', 3),
    (240, 'Stray','TapiocaKing',5,0,'Season 3','Stray', 3),
    (241, 'Afflatus Misery','Ol[d]cadan',5,3,'Season 3','Afflatus Misery', 3),
    (242, 'Hazu','Lyonide',5,3,'Season 3','Hazu', 3),
    (243, 'Domitto','Spirit410',5,1,'Season 3','Domitto', 3),
    (244, 'Carriacou','Tadlos',5,0,'Season 3','Carriacou', 3),
    (245, 'Blade of Flame','Taokaka Meow',5,2,'Season 3','Blade of Flame', 3),
    (246, 'MonkeyKing','Valhanya',5,4,'Season 3','MonkeyKing', 3),
    (247, 'Ganondeurf','Neon',5,3,'Season 3','Ganondeurf', 3),
    (248, 'Horken','Momotehk',5,2,'Season 3','Horken', 3),
    (249, 'Aby','Lyonide',5,4,'Season 3','Aby', 3),
    (250, 'Taz','Zollith',5,4,'Season 3','Taz', 3),
    (251, 'Spirit410','WorldBranstar',10,4,'Season 3','Spirit410', 3),
    (252, 'MonkeyKing','Fotten',5,0,'Season 3','MonkeyKing', 3),
    (253, 'LozKias','WorldBranstar',5,0,'Season 3','LozKias', 3),
    (254, 'Ssylus','Ganondeurf',5,0,'Season 3','Ssylus', 3),
    (255, 'D3xus','Aelz',5,0,'Season 3','D3xus', 3),
    (257, 'Lyonide','Iona Rose',5,1,'Season 4','Lyonide', 4),
    (258, 'Stray','Aby',4,2,'Season 4','Stray', 4),
    (259, 'Zanaken','Fotten',5,4,'Season 4','Zanaken', 4),
    (260, 'Guilu','Sett',5,4,'Season 4','Guilu', 4),
    (261, 'The Arpeggiator','Momotehk',5,0,'Season 4','The Arpeggiator', 4),
    (262, 'Kellerak','polosaty',5,1,'Season 4','Kellerak', 4),
    (263, 'VileMuffin','Zephyrion',5,1,'Season 4','VileMuffin', 4),
    (264, 'Ventras','WorldBranstar',5,1,'Season 4','Ventras', 4),
    (265, 'Amancio Ortega','Jumpie',5,1,'Season 4','Amancio Ortega', 4),
    (266, 'Unicorn','Afflatus Misery',5,4,'Season 4','Unicorn', 4),
    (267, 'Hazu','Stray',5,0,'Season 4','Hazu', 4),
    (268, 'Darxy','Valhanya',5,4,'Season 4','Darxy', 4),
    (269, 'MPhantasm','The Arpeggiator',5,3,'Season 4','MPhantasm', 4),
    (270, 'Tadlos','Pikapi',5,3,'Season 4','Tadlos', 4),
    (271, 'Fotten','Taokaka Meow',5,3,'Season 4','Fotten', 4),
    (272, 'Skyll','D3xus',10,5,'Season 4','Skyll', 4),
    (273, 'Kellerak','Drunky',5,2,'Season 4','Kellerak', 4),
    (274, 'Lyonide','Cpt-GI',5,2,'Season 4','Lyonide', 4),
    (275, 'Guilu','LozKias',5,2,'Season 4','Guilu', 4),
    (276, 'Momotehk','polosaty',5,4,'Season 4','Momotehk', 4),
    (277, 'Zollith','Zephyrion',5,4,'Season 4','Zollith', 4),
    (278, 'Sett','Ventras',5,2,'Season 4','Sett', 4),
    (279, 'Habaduba','DarthSeppius',10,2,'Season 4','Habaduba', 4),
    (280, 'Amancio Ortega','Tadlos',5,0,'Season 4','Amancio Ortega', 4),
    (281, 'Zollith','Lyonide',5,2,'Season 4','Zollith', 4),
    (282, 'Hazu','Jazair',5,2,'Season 4','Hazu', 4),
    (283, 'D3xus','Aarpia',10,3,'Season 4','D3xus', 4),
    (284, 'Momotehk','Miha Senju',5,3,'Season 4','Momotehk', 4),
    (285, 'Kellerak','Aby',5,1,'Season 4','Kellerak', 4),
    (286, 'Taokaka Meow','Graveryl',5,2,'Season 4','Taokaka Meow', 4),
    (287, 'Domitto','Baddy',5,3,'Season 4','Domitto', 4),
    (288, 'Fotten','Hazu',5,4,'Season 4','Fotten', 4),
    (289, 'Sett','Guilu',10,9,'Season 4','Sett', 4),
    (290, 'Aelz','Ssylus',10,2,'Season 4','Aelz', 4),
    (291, 'Jumpie','REKORDER',5,0,'Season 4','Jumpie', 4),
    (292, 'Amancio Ortega','Afflatus Misery',5,3,'Season 4','Amancio Ortega', 4),
    (293, 'Taokaka Meow','Jazair',5,2,'Season 4','Taokaka Meow', 4),
    (294, 'Blade of Flame','Ventras',4,1,'Season 4','Blade of Flame', 4),
    (295, 'Hamidumi','Miha Senju',5,1,'Season 4','Hamidumi', 4),
    (296, 'Greywall','polosaty',5,0,'Season 4','Greywall', 4),
    (297, 'Cpt-GI','Momotehk',5,1,'Season 4','Cpt-GI', 4),
    (298, 'Lyonide','Aby',5,1,'Season 4','Lyonide', 4),
    (299, 'Habaduba','Spirit410',5,2,'Season 4','Habaduba', 4),
    (300, 'Nins','REKORDER',5,1,'Season 4','Nins', 4),
    (301, 'Lyonide','Jazair',5,2,'Season 4','Lyonide', 4),
    (302, 'Fotten','Fanlee Jr',5,4,'Season 4','Fotten', 4),
    (303, 'Ganondeurf','Aarpia',10,9,'Season 4','Ganondeurf', 4),
    (304, 'Afflatus Misery','Momotehk',5,1,'Season 4','Afflatus Misery', 4),
    (305, 'SHeF-87','Zephyrion',5,2,'Season 4','SHeF-87', 4),
    (306, 'Kellerak','Sekirei',5,4,'Season 4','Kellerak', 4),
    (307, 'Guilu','Darxy',10,2,'Season 4','Guilu', 4),
    (308, 'Aby','dopppa',5,1,'Season 4','Aby', 4),
    (309, 'Zollith','SpartanTigra',5,4,'Season 4','Zollith', 4),
    (310, 'Sett','Spirit410',5,1,'Season 4','Sett', 4),
    (311, 'Mental','Tadlos',5,4,'Season 4','Mental', 4),
    (312, 'VileMuffin','Taokaka Meow',5,0,'Season 4','VileMuffin', 4),
    (313, 'LozKias','MonkeyKing',5,2,'Season 4','LozKias', 4),
    (314, 'Yin','Domitto',5,2,'Season 4','Yin', 4),
    (315, 'Nins','Jumpie',5,4,'Season 4','Nins', 4),
    (316, 'Deyan87','Faultroll',5,4,'Season 4','Deyan87', 4),
    (317, 'Fanlee Jr','LEV77',5,1,'Season 4','Fanlee Jr', 4),
    (318, 'Ventras','Hazu',5,2,'Season 4','Ventras', 4),
    (319, 'Afflatus Misery','Mental',5,3,'Season 4','Afflatus Misery', 4),
    (320, 'Lyonide','Graveryl',5,2,'Season 4','Lyonide', 4),
    (321, 'Zollith','Fotten',5,2,'Season 4','Zollith', 4),
    (322, 'Raziel','Ssylus',5,2,'Season 4','Raziel', 4),
    (323, 'PanPan','Tadlos',5,4,'Season 4','PanPan', 4),
    (324, 'Valhanya','Billflop',5,3,'Season 4','Valhanya', 4),
    (325, 'Kellerak','Taokaka Meow',5,4,'Season 4','Kellerak', 4),
    (326, 'LozKias','Blade of Flame',5,1,'Season 4','LozKias', 4),
    (327, 'Tadlos','Pikapi',5,0,'Season 4','Tadlos', 4),
    (328, 'Amancio Ortega','Kusoge',5,0,'Season 4','Amancio Ortega', 4),
    (329, 'Billflop','Afflatus Misery',5,1,'Season 4','Billflop', 4),
    (330, 'Sekirei','Nashley',5,0,'Season 4','Sekirei', 4),
    (331, 'Hazu','WorldBranstar',5,0,'Season 4','Hazu', 4),
    (332, 'Guilu','Sett',10,2,'Season 4','Guilu', 4),
    (333, 'Yin','Ganondeurf',5,0,'Season 4','Yin', 4),
    (334, 'Skyll','Aelz',10,3,'Season 4','Skyll', 4),
    (335, 'Afflatus Misery','Unicorn',5,4,'Season 5','Afflatus Misery', 5),
    (336, 'Hazu','VileMuffin',5,2,'Season 5','Hazu', 5),
    (337, 'D3xus','DarthSeppius',5,1,'Season 5','D3xus', 5),
    (338, 'Aby','Iona Rose',5,1,'Season 5','Aby', 5),
    (339, 'Lyonide','Kellerak',5,3,'Season 5','Lyonide', 5),
    (340, 'Domitto','Ganondeurf',5,4,'Season 5','Domitto', 5),
    (341, 'Sonder','Horken',5,2,'Season 5','Sonder', 5),
    (342, 'Freemard','SHeF-87',5,0,'Season 5','Freemard', 5),
    (343, 'Taokaka Meow','Aby',5,3,'Season 5','Taokaka Meow', 5),
    (344, 'WorldBranstar','Kellerak',5,0,'Season 5','WorldBranstar', 5),
    (345, 'LozKias','Lyonide',5,3,'Season 5','LozKias', 5),
    (346, 'Tadlos','Jumpie',5,2,'Season 5','Tadlos', 5),
    (347, 'Rosa','Sekirei',5,2,'Season 5','Rosa', 5),
    (348, 'Fotten','Darxy',5,0,'Season 5','Fotten', 5),
    (349, 'DarthSeppius','Habaduba',5,4,'Season 5','DarthSeppius', 5),
    (350, 'D3xus','Ssylus',5,2,'Season 5','D3xus', 5),
    (351, 'Gaspar','Tadlos',5,0,'Season 5','Gaspar', 5),
    (352, 'Aby','Afflatus Misery',5,3,'Season 5','Aby', 5),
    (353, 'Fotten','Mental',5,3,'Season 5','Fotten', 5),
    (354, 'WorldBranstar','SpartanTigra',5,3,'Season 5','WorldBranstar', 5),
    (355, 'Sett','Lyonide',5,2,'Season 5','Sett', 5),
    (356, 'The Arpeggiator','Jumpie',5,0,'Season 5','The Arpeggiator', 5),
    (357, 'Freemard','Zollith',5,1,'Season 5','Freemard', 5),
    (358, 'Ssylus','Habaduba',5,0,'Season 5','Ssylus', 5),
    (359, 'Tadlos','TapiocaKing',5,1,'Season 5','Tadlos', 5),
    (360, 'Stray','The Arpeggiator',5,4,'Season 5','Stray', 5),
    (361, 'Kellerak','SpartanTigra',5,4,'Season 5','Kellerak', 5),
    (362, 'Ganondeurf','DarthSeppius',5,2,'Season 5','Ganondeurf', 5),
    (363, 'Junky','SiloZen',5,2,'Season 5','Junky', 5),
    (364, 'Jumpie','X-Ray',5,2,'Season 5','Jumpie', 5),
    (365, 'Sonder','Patrick',5,2,'Season 5','Sonder', 5),
    (366, 'Freemard','Fotten',5,2,'Season 5','Freemard', 5),
    (367, 'Ssylus','Blade of Flame',5,2,'Season 5','Ssylus', 5),
    (368, 'Sonder','SomethingRefined',5,1,'Season 5','Sonder', 5),
    (369, 'Mental','WorldBranstar',5,4,'Season 5','Mental', 5),
    (370, 'Sekirei','SpartanTigra',5,1,'Season 5','Sekirei', 5),
    (371, 'Ganondeurf','Ssylus',5,4,'Season 5','Ganondeurf', 5),
    (372, 'Patrick','Volty',5,3,'Season 5','Patrick', 5),
    (373, 'ZER0','Tadlos',5,3,'Season 5','ZER0', 5),
    (374, 'Fotten','Lyonide',5,4,'Season 5','Fotten', 5),
    (375, 'Valhanya','Kellerak',5,1,'Season 5','Valhanya', 5),
    (376, 'Freemard','Sett',5,3,'Season 5','Freemard', 5),
    (377, 'X-Ray','SomethingRefined',5,4,'Season 5','X-Ray', 5),
    (378, 'Momotehk','Jumpie',5,4,'Season 5','Momotehk', 5),
    (379, 'Patrick','Frieden',5,1,'Season 5','Patrick', 5),
    (380, 'VileMuffin','Taokaka Meow',5,1,'Season 5','VileMuffin', 5),
    (381, 'Ganondeurf','Baddy',5,1,'Season 5','Ganondeurf', 5),
    (382, 'Mental','Kellerak',5,4,'Season 5','Mental', 5),
    (383, 'Tadlos','X-Ray',5,1,'Season 5','Tadlos', 5),
    (384, 'SomethingRefined','Volty',5,4,'Season 5','SomethingRefined', 5),
    (385, 'Fotten','VileMuffin',5,4,'Season 5','Fotten', 5),
    (386, 'Aby','SpartanTigra',5,0,'Season 5','Aby', 5),
    (387, 'Jumpie','Junky',5,0,'Season 5','Jumpie', 5),
    (388, 'Yin','Ssylus',5,1,'Season 5','Yin', 5),
    (389, 'SomethingRefined','Horken',5,1,'Season 5','SomethingRefined', 5),
    (390, 'Lars','FateKuru',5,0,'Season 5','Lars', 5),
    (391, 'Volty','Jumpie',5,2,'Season 5','Volty', 5),
    (392, 'Lyonide','LEV77',5,2,'Season 5','Lyonide', 5),
    (393, 'Mental','Afflatus Misery',5,3,'Season 5','Mental', 5),
    (394, 'Kellerak','The Arpeggiator',5,1,'Season 5','Kellerak', 5),
    (395, 'Momotehk','X-Ray',5,3,'Season 5','Momotehk', 5),
    (396, 'Sett','Lyonide',5,3,'Season 5','Sett', 5),
    (397, 'WorldBranstar','Necrologen',5,3,'Season 5','WorldBranstar', 5),
    (398, 'Zollith','Aby',5,2,'Season 5','Zollith', 5),
    (399, 'Gaspar','Jumpie',5,1,'Season 5','Gaspar', 5),
    (400, 'X-Ray','Junky',5,3,'Season 5','X-Ray', 5),
    (401, 'Habaduba','Ganondeurf',5,3,'Season 5','Habaduba', 5),
    (402, 'Rosa','Raziel',5,4,'Season 5','Rosa', 5),
    (403, 'WorldBranstar','Patrick',5,3,'Season 5','WorldBranstar', 5),
    (404, 'Kellerak','SpartanTigra',5,2,'Season 5','Kellerak', 5),
    (405, 'Volty','X-Ray',5,2,'Season 5','Volty', 5),
    (406, 'LEV77','Fotten',5,4,'Season 5','LEV77', 5),
    (407, 'Ozhora','Jumpie',5,4,'Season 5','Ozhora', 5),
    (408, 'Freemard','Lyonide',5,2,'Season 5','Freemard', 5),
    (409, 'Kellerak','JabberJayJay',5,3,'Season 5','Kellerak', 5),
    (410, 'Scarlet','X-Ray',5,2,'Season 5','Scarlet', 5),
    (411, 'The Arpeggiator','Momotehk',5,2,'Season 5','The Arpeggiator', 5),
    (412, 'Ssylus','DarthSeppius',5,1,'Season 5','Ssylus', 5),
    (413, 'Freemard','LozKias',5,2,'Season 5','Freemard', 5),
    (414, 'Mental','The Arpeggiator',5,3,'Season 5','Mental', 5),
    (415, 'Scarlet','AutobahnAlpha',5,1,'Season 5','Scarlet', 5),
    (416, 'WorldBranstar','JabberJayJay',5,4,'Season 5','WorldBranstar', 5),
    (417, 'Tadlos','Afflatus Misery',5,4,'Season 5','Tadlos', 5),
    (418, 'MonkeyKing','X-Ray',5,3,'Season 5','MonkeyKing', 5),
    (419, 'Ganondeurf','WorldBranstar',10,7,'Season 5','Ganondeurf', 5),
    (420, 'Ssylus','Noobycide',5,3,'Season 5','Ssylus', 5),
    (421, 'Freemard','Aby',5,1,'Season 5','Freemard', 5),
    (422, 'Lyonide','Scarlet',5,4,'Season 5','Lyonide', 5),
    (423, 'Fanlee Jr','DarthSeppius',10,3,'Season 5','Fanlee Jr', 5),
    (424, 'Scarlet','Afflatus Misery',5,0,'Season 5','Scarlet', 5),
    (425, 'Ssylus','Fotten',10,2,'Season 5','Ssylus', 5),
    (426, 'Zollith','Jumpie',5,1,'Season 5','Zollith', 5),
    (427, 'Momotehk','Junky',5,0,'Season 5','Momotehk', 5),
    (428, 'Ssylus','WorldBranstar',5,1,'Season 5','Ssylus', 5),
    (429, 'DarthSeppius','MonkeyKing',5,3,'Season 5','DarthSeppius', 5),
    (430, 'Scarlet','Nashley',5,1,'Season 5','Scarlet', 5),
    (431, 'Aby','Afflatus Misery',10,6,'Season 5','Aby', 5),
    (432, 'Afflatus Misery','Patrick',10,9,'Season 5','Afflatus Misery', 5),
    (433, 'SomethingRefined','Tadlos',5,0,'Season 5','SomethingRefined', 5),
    (434, 'Rosa','Lyonide',10,0,'Season 5','Rosa', 5),
    (435, 'Scarlet','Tadlos',5,1,'Season 5','Scarlet', 5),
    (436, 'Scarlet','DarthSeppius',5,4,'Season 5','Scarlet', 5),
    (437, 'SomethingRefined','Afflatus Misery',5,3,'Season 5','SomethingRefined', 5),
    (438, 'Tadlos','Samurai',5,0,'Season 5','Tadlos', 5),
    (439, 'Jumpie','Metabee',5,2,'Season 5','Jumpie', 5),
    (440, 'WorldBranstar','Rosa',5,3,'Season 5','WorldBranstar', 5),
    (441, 'Freemard','Sett',5,1,'Season 5','Freemard', 5),
    (442, 'Kellerak','Zollith',5,1,'Season 5','Kellerak', 5),
    (443, 'X-Ray','TotemGenbu',5,2,'Season 5','X-Ray', 5),
    (444, 'Athena','DarthSeppius',5,2,'Season 5','Athena', 5),
    (445, 'Taokaka Meow','Gaspar',5,3,'Season 5','Taokaka Meow', 5),
    (446, 'Momotehk','Tadlos',5,1,'Season 5','Momotehk', 5),
    (447, 'X-Ray','Samurai',5,0,'Season 5','X-Ray', 5),
    (448, 'Aby','Baddy',5,2,'Season 5','Aby', 5),
    (449, 'Mental','Jumpie',5,3,'Season 5','Mental', 5),
    (450, 'Pikapi','TotemGenbu',5,4,'Season 5','Pikapi', 5),
    (451, 'Ganondeurf','Athena',5,4,'Season 5','Ganondeurf', 5),
    (452, 'Gaspar','Jumpie',5,0,'Season 5','Gaspar', 5),
    (453, 'Mental','Aby',5,4,'Season 5','Mental', 5),
    (454, 'Hajin','Momotehk',5,4,'Season 5','Hajin', 5),
    (455, 'Freemard','DarthSeppius',5,2,'Season 5','Freemard', 5),
    (456, 'Taokaka Meow','The Arpeggiator',5,2,'Season 5','Taokaka Meow', 5),
    (457, 'TotemGenbu','Kellerak',5,3,'Season 5','TotemGenbu', 5),
    (458, 'Horken','X-Ray',5,0,'Season 5','Horken', 5),
    (459, 'Hajin','Pikapi',5,1,'Season 5','Hajin', 5),
    (460, 'Jumpie','Tadlos',5,4,'Season 5','Jumpie', 5),
    (461, 'X-Ray','Goatreich',5,2,'Season 5','X-Ray', 5);

  -- Create archived seasons for historical data (IDs 1-5)
  INSERT INTO seasons(id, name, status, start_date, description)
  VALUES (1, 'Season 1', 'archived', NOW(), 'Historical season: Season 1')
  ON CONFLICT(id) DO UPDATE SET status = 'archived';
  INSERT INTO seasons(id, name, status, start_date, description)
  VALUES (2, 'Season 2', 'archived', NOW(), 'Historical season: Season 2')
  ON CONFLICT(id) DO UPDATE SET status = 'archived';
  INSERT INTO seasons(id, name, status, start_date, description)
  VALUES (3, 'Season 3', 'archived', NOW(), 'Historical season: Season 3')
  ON CONFLICT(id) DO UPDATE SET status = 'archived';
  INSERT INTO seasons(id, name, status, start_date, description)
  VALUES (4, 'Season 4', 'archived', NOW(), 'Historical season: Season 4')
  ON CONFLICT(id) DO UPDATE SET status = 'archived';
  INSERT INTO seasons(id, name, status, start_date, description)
  VALUES (5, 'Season 5', 'archived', NOW(), 'Historical season: Season 5')
  ON CONFLICT(id) DO UPDATE SET status = 'archived';

  -- Create new active season (ID 0) - CRITICAL: Ensure it is marked as active (status='active')
  -- This must DELETE and re-INSERT to override any existing record
  DELETE FROM seasons WHERE id = 0;
  INSERT INTO seasons(id, name, status, start_date, description)
  VALUES (0, 'Active Season', 'active', NOW(), 'Current active season');
  
  -- Ensure ALL other seasons are archived (not active)
  UPDATE seasons SET status = 'archived' WHERE id != 0;

  -- Insert unique events
  INSERT INTO events(title, event_date)
  SELECT DISTINCT event, NOW()
    FROM seeddata
  WHERE 
    NOT EXISTS(
      SELECT 1
      FROM events AS E
      WHERE E.title = seeddata.event
    )
  ORDER BY event;

  -- Insert unique players (all with NULL ratings initially)
  INSERT INTO players(name)
  SELECT DISTINCT name
    FROM (
      SELECT player1 as name FROM seeddata
      UNION SELECT player2 FROM seeddata
    ) AS T
  WHERE 
    NOT EXISTS(
      SELECT 1
      FROM players AS P
      WHERE P.name = T.name
    );

  -- Update player twitter profiles
  UPDATE players SET twitter = 'unicorn_cz' WHERE name = 'Unicorn';
  UPDATE players SET twitter = 'SC_MercyMainBTW' WHERE name = 'MercyMainBTW';
  UPDATE players SET twitter = 'Taokaka__Meow' WHERE name = 'Taokaka Meow';
  UPDATE players SET twitter = 'simon95lb' WHERE name = 'The Arpeggiator';
  UPDATE players SET twitter = 'yangin_pikapi' WHERE name = 'Pikapi';
  UPDATE players SET twitter = 'Winterwander' WHERE name = 'HawkOfGP';
  UPDATE players SET twitter = 'HolyCarpSC' WHERE name = 'HolyCarp';
  UPDATE players SET twitter = 'PyrrhoZaydan' WHERE name = 'Zaydan';
  UPDATE players SET twitter = 'Myloes_' WHERE name = 'Myloes';
  UPDATE players SET twitter = 'NeonFGC' WHERE name = 'Neon';
  UPDATE players SET twitter = 'MPhantasmF' WHERE name = 'MPhantasm';
  UPDATE players SET twitter = 'Aarpia1' WHERE name = 'Aarpia';
  UPDATE players SET twitter = 'Skyll_13' WHERE name = 'Skyll';
  UPDATE players SET twitter = 'Aelz9' WHERE name = 'Aelz';
  UPDATE players SET twitter = 'Darxity_' WHERE name = 'Darxy';
  UPDATE players SET twitter = 'D3xusSC' WHERE name = 'D3xus';
  UPDATE players SET twitter = 'SiloZen' WHERE name = 'SiloZen';
  UPDATE players SET twitter = 'Blade_of_Flame' WHERE name = 'Blade of Flame';
  UPDATE players SET twitter = 'DarkWraithZER0' WHERE name = 'ZER0';
  UPDATE players SET twitter = 'habaduba' WHERE name = 'Habaduba';
  UPDATE players SET twitter = 'SirRefined' WHERE name = 'SomethingRefined';
  UPDATE players SET twitter = 'FottenSC' WHERE name = 'Fotten';
  UPDATE players SET twitter = 'Ssylus1' WHERE name = 'Ssylus';
  UPDATE players SET twitter = 'Nashl3y' WHERE name = 'Nashley';
  UPDATE players SET twitter = 'Lyonide' WHERE name = 'Lyonide';
  UPDATE players SET twitter = 'WorldBranstar' WHERE name = 'WorldBranstar';
  UPDATE players SET twitter = 'lozkias' WHERE name = 'LozKias';
  UPDATE players SET twitter = 'ganondeurfT' WHERE name = 'Ganondeurf';

  -- Insert match data with appropriate season_id (historical matches to archived seasons)
  INSERT INTO matches(
    player1_id, player1_score,
    player2_id, player2_score, 
    winner_id, event_id, 
    match_order,
    season_id
  )
  SELECT
    P1.id, S.player1score,
    P2.id, S.player2score,
    W.id,
    E.id,
    S.row_index,
    S.season_id
  FROM seeddata as S
  INNER JOIN players AS P1 ON P1.name = S.player1
  INNER JOIN players AS P2 ON P2.name = S.player2
  INNER JOIN players AS W ON W.name = S.winner
  INNER JOIN events AS E ON E.title = S.event
  ORDER BY S.row_index;

  DROP TABLE seeddata;

  UPDATE matches
  SET vod_link = 'https://www.youtube.com/shorts/IZMaHVVIObs';

  UPDATE events
  SET vod_link = 'https://youtu.be/1sFbLppuhhs?si=JUlABkFdrF5MYYvy';
END $$;
