-- Seed data generated from sampleData.csv
-- Total matches: 459
-- Total events: 5

DO $$
BEGIN
  DROP TABLE IF EXISTS seeddata;
  CREATE TEMP TABLE seeddata(
    row_index INT,
    player1 varchar(128),
    player2 varchar(128),
    player1score INT,
    player2score INT,
    event varchar(128),
    winner varchar(128)
  );

  INSERT INTO seeddata (row_index, player1, player2, player1score, player2score, event, winner) 
  VALUES
    (1, 'MonkeyKing','Fon',5,2,'Season 1','MonkeyKing'),
    (2, 'dopppa','Terachi',5,2,'Season 1','dopppa'),
    (3, 'Spirit410','Domitto',10,6,'Season 1','Spirit410'),
    (4, 'Prizvel','Cpt-GI',5,3,'Season 1','Prizvel'),
    (5, 'Mozarus','Spear',5,3,'Season 1','Mozarus'),
    (6, 'Stray','SHARK',5,0,'Season 1','Stray'),
    (7, 'Ol[d]cadan','Polosaty',5,1,'Season 1','Ol[d]cadan'),
    (8, 'Hamidumi','Carnhulio',5,3,'Season 1','Hamidumi'),
    (9, 'D3xus','Habaduba',10,3,'Season 1','D3xus'),
    (10, 'MPhantasm','Vegasvat',5,1,'Season 1','MPhantasm'),
    (11, 'Taokaka Meow','Jc_near',5,3,'Season 1','Taokaka Meow'),
    (12, 'Baddy','Valhanya',5,4,'Season 1','Baddy'),
    (13, 'Ganondeurf','Yin',10,7,'Season 1','Ganondeurf'),
    (14, 'SHARK','K.D.C.',5,1,'Season 1','SHARK'),
    (15, 'Stray','TapiocaKing',5,1,'Season 1','Stray'),
    (16, 'VileMuffin','Prizvel',5,0,'Season 1','VileMuffin'),
    (17, 'dopppa','Hamidumi',5,2,'Season 1','dopppa'),
    (18, 'Rufus','Aelz',5,3,'Season 1','Rufus'),
    (19, 'Cpt-GI','Polosaty',5,1,'Season 1','Cpt-GI'),
    (20, 'Volty','TangAce',5,0,'Season 1','Volty'),
    (21, 'Fotten','Zephyrion',5,0,'Season 1','Fotten'),
    (22, 'Guilu','Sett',5,1,'Season 1','Guilu'),
    (23, 'Ssylus','Andyroo',10,3,'Season 1','Ssylus'),
    (24, 'Azizure','Taz',5,4,'Season 1','Azizure'),
    (25, 'Graveryl','Momotehk',5,1,'Season 1','Graveryl'),
    (26, 'Sett','Doktai',5,4,'Season 1','Sett'),
    (27, 'Sams','Habaduba',10,6,'Season 1','Sams'),
    (28, 'PanPan','Yuusha42',5,4,'Season 1','PanPan'),
    (29, 'VileMuffin','Taokaka Meow',5,4,'Season 1','VileMuffin'),
    (30, 'Ceiwen','Sekirei',5,3,'Season 1','Ceiwen'),
    (31, 'Domitto','Neon',10,8,'Season 1','Domitto'),
    (32, 'Spear','Hamidumi',5,0,'Season 1','Spear'),
    (33, 'Zephyrion','SHARK',5,2,'Season 1','Zephyrion'),
    (34, 'Volty','Ennvill',5,4,'Season 1','Volty'),
    (35, 'Vegasvat','Ol[d]cadan',5,3,'Season 1','Vegasvat'),
    (36, 'Guilu','MonkeyKing',5,0,'Season 1','Guilu'),
    (37, 'Valhanya','Carnhulio',5,0,'Season 1','Valhanya'),
    (38, 'Ganondeurf','Spirit410',5,2,'Season 1','Ganondeurf'),
    (39, 'Carriacou','TapiocaKing',5,0,'Season 1','Carriacou'),
    (40, 'Aby','Stray',5,3,'Season 1','Aby'),
    (41, 'Baddy','Mozarus',5,1,'Season 1','Baddy'),
    (42, 'Aarpia','DarthSeppius',10,4,'Season 1','Aarpia'),
    (43, 'SHARK','Tadlos',5,4,'Season 1','SHARK'),
    (44, 'MonkeyKing','Terachi',5,1,'Season 1','MonkeyKing'),
    (45, 'Azizure','dopppa',5,1,'Season 1','Azizure'),
    (46, 'ZappySoyou','Spirit410',5,3,'Season 1','ZappySoyou'),
    (47, 'Jazair','Prizvel',5,0,'Season 1','Jazair'),
    (48, 'Carriacou','Stray',5,4,'Season 1','Carriacou'),
    (49, 'Carnhulio','Vegasvat',5,4,'Season 1','Carnhulio'),
    (50, 'D3xus','Aelz',10,1,'Season 1','D3xus'),
    (51, 'Zephyrion','PanPan',5,0,'Season 1','Zephyrion'),
    (52, 'Taz','Sekirei',5,2,'Season 1','Taz'),
    (53, 'Nickvold','TapiocaKing',5,3,'Season 1','Nickvold'),
    (54, 'Ventras','Hamidumi',5,0,'Season 1','Ventras'),
    (55, 'Sett','VileMuffin',5,2,'Season 1','Sett'),
    (56, 'D3xus','Ssylus',5,3,'Season 1','D3xus'),
    (57, 'Doktai','Aby',5,1,'Season 1','Doktai'),
    (58, 'Volty','Ryuki',5,1,'Season 1','Volty'),
    (59, 'Algernon','Taokaka Meow',5,3,'Season 1','Algernon'),
    (60, 'Domitto','DarthSeppius',10,9,'Season 1','Domitto'),
    (61, 'Blade of Flame','LozKias',5,1,'Season 1','Blade of Flame'),
    (62, 'Fanlee Jr','Ceiwen',5,3,'Season 1','Fanlee Jr'),
    (63, 'Baddy','Zollith',5,3,'Season 1','Baddy'),
    (64, 'Aarpia','HolyCarp',5,0,'Season 1','Aarpia'),
    (65, 'Jazair','Doktai',5,0,'Season 1','Jazair'),
    (66, 'Stray','Nickvold',5,0,'Season 1','Stray'),
    (67, 'MonkeyKing','Graveryl',5,3,'Season 1','MonkeyKing'),
    (68, 'Algernon','dopppa',5,2,'Season 1','Algernon'),
    (69, 'polosaty','Ennvill',5,3,'Season 1','polosaty'),
    (70, 'Yaj-Ly','Ryuki',5,1,'Season 1','Yaj-Ly'),
    (71, 'Zanaken','Volty',5,1,'Season 1','Zanaken'),
    (72, 'Rufus','DarthSeppius',10,1,'Season 1','Rufus'),
    (73, 'Prizvel','Vegasvat',5,1,'Season 1','Prizvel'),
    (74, 'VileMuffin','Ventras',5,4,'Season 1','VileMuffin'),
    (75, 'LozKias','Taz',5,2,'Season 1','LozKias'),
    (76, 'Ceiwen','Azizure',5,1,'Season 1','Ceiwen'),
    (77, 'PanPan','Momotehk',5,4,'Season 1','PanPan'),
    (78, 'Hazu','Zollith',5,0,'Season 1','Hazu'),
    (79, 'Zaydan','Taokaka Meow',5,4,'Season 1','Zaydan'),
    (80, 'Neon','Habaduba',10,8,'Season 1','Neon'),
    (81, 'Sett','Valhanya',5,2,'Season 1','Sett'),
    (82, 'Baddy','Guilu',10,4,'Season 1','Baddy'),
    (83, 'Aelz','ZappySoyou',5,1,'Season 1','Aelz'),
    (84, 'Ssylus','Domitto',5,3,'Season 1','Ssylus'),
    (85, 'D3xus','Ganondeurf',10,5,'Season 1','D3xus'),
    (86, 'SHARK','TapiocaKing',5,2,'Season 2','SHARK'),
    (87, 'HawkOfGP','Carriacou',5,1,'Season 2','HawkOfGP'),
    (88, 'Danurai','Aby',5,4,'Season 2','Danurai'),
    (89, 'Yin','Andyroo',10,7,'Season 2','Yin'),
    (90, 'Ventras','Taokaka Meow',5,0,'Season 2','Ventras'),
    (91, 'Yaj-Ly','PanPan',5,4,'Season 2','Yaj-Ly'),
    (92, 'Graveryl','Rosa',5,1,'Season 2','Graveryl'),
    (93, 'DarthSeppius','Baddy',10,9,'Season 2','DarthSeppius'),
    (94, 'Aby','The Arpeggiator',5,3,'Season 2','Aby'),
    (95, 'Blade of Flame','Jazair',5,3,'Season 2','Blade of Flame'),
    (96, 'Sett','Habaduba',5,3,'Season 2','Sett'),
    (97, 'D3xus','Aarpia',10,7,'Season 2','D3xus'),
    (98, 'Stray','polosaty',5,4,'Season 2','Stray'),
    (99, 'Volty','Carriacou',5,3,'Season 2','Volty'),
    (100, 'Mozarus','Hazu',5,3,'Season 2','Mozarus'),
    (101, 'Aelz','Domitto',10,5,'Season 2','Aelz'),
    (102, 'Ryuki','Tadlos',5,3,'Season 2','Ryuki'),
    (103, 'Polosaty','TapiocaKing',5,0,'Season 2','Polosaty'),
    (104, 'Ventras','Volty',5,0,'Season 2','Ventras'),
    (105, 'VileMuffin','Habaduba',5,1,'Season 2','VileMuffin'),
    (106, 'Momotehk','The Arpeggiator',5,0,'Season 2','Momotehk'),
    (107, 'Algernon','Ceiwen',5,2,'Season 2','Algernon'),
    (108, 'Doktai','Graveryl',5,3,'Season 2','Doktai'),
    (109, 'Domitto','ZER0',5,4,'Season 2','Domitto'),
    (110, 'Ennvill','Prizvel',5,4,'Season 2','Ennvill'),
    (111, 'Carnhulio','dopppa',5,3,'Season 2','Carnhulio'),
    (112, 'MonkeyKing','Mozarus',5,2,'Season 2','MonkeyKing'),
    (113, 'Neon','ZappySoyou',5,2,'Season 2','Neon'),
    (114, 'Lyonide','Dzing',5,4,'Season 2','Lyonide'),
    (115, 'Aby','Zephyrion',5,3,'Season 2','Aby'),
    (116, 'Sett','Baddy',10,8,'Season 2','Sett'),
    (117, 'PanPan','Fergus',5,2,'Season 2','PanPan'),
    (118, 'Zephyrion','Volty',5,2,'Season 2','Zephyrion'),
    (119, 'Ventras','Mozarus',5,1,'Season 2','Ventras'),
    (120, 'Baddy','VileMuffin',5,4,'Season 2','Baddy'),
    (121, 'Ol[d]cadan','Nickvold',5,0,'Season 2','Ol[d]cadan'),
    (122, 'Prizvel','Kreozot',5,3,'Season 2','Prizvel'),
    (123, 'Polosaty','Sonder',5,1,'Season 2','Polosaty'),
    (124, 'Algernon','MonkeyKing',5,1,'Season 2','Algernon'),
    (125, 'Habaduba','Blade of Flame',5,0,'Season 2','Habaduba'),
    (126, 'Stray','Sonder',5,3,'Season 2','Stray'),
    (127, 'Lyonide','Aby',5,3,'Season 2','Lyonide'),
    (128, 'Aelz','Ssylus',10,9,'Season 2','Aelz'),
    (129, 'ZappySoyou','Sett',5,2,'Season 2','ZappySoyou'),
    (130, 'Aarpia','ZER0',5,0,'Season 2','Aarpia'),
    (131, 'Aelz','D3xus',10,5,'Season 2','Aelz'),
    (133, 'MonkeyKing','Polosaty',5,1,'Season 2','MonkeyKing'),
    (134, 'Zephyrion','Stray',5,2,'Season 2','Zephyrion'),
    (135, 'Lyonide','Taz',5,3,'Season 2','Lyonide'),
    (136, 'Baddy','Algernon',10,8,'Season 2','Baddy'),
    (137, 'Tadlos','Nickvold',5,0,'Season 2','Tadlos'),
    (138, 'LozKias','Doktai',5,4,'Season 2','LozKias'),
    (139, 'PanPan','Volty',5,4,'Season 2','PanPan'),
    (140, 'Habaduba','Ventras',5,4,'Season 2','Habaduba'),
    (141, 'Sonder','Pikapi',5,0,'Season 2','Sonder'),
    (142, 'Polosaty','Finzy',5,2,'Season 2','Polosaty'),
    (143, 'Habaduba','LozKias',5,3,'Season 2','Habaduba'),
    (144, 'D3xus','Domitto',5,1,'Season 2','D3xus'),
    (145, 'ETS','Nickvold',5,1,'Season 2','ETS'),
    (146, 'PanPan','Sekirei',5,2,'Season 2','PanPan'),
    (147, 'VileMuffin','MonkeyKing',5,3,'Season 2','VileMuffin'),
    (148, 'Andyroo','Baddy',10,8,'Season 2','Andyroo'),
    (149, 'Dzing','Vincent',5,4,'Season 2','Dzing'),
    (150, 'Graveryl','Zephyrion',5,1,'Season 2','Graveryl'),
    (151, 'Ventras','Lyonide',5,4,'Season 2','Ventras'),
    (152, 'Guilu','Zanaken',5,3,'Season 2','Guilu'),
    (153, 'Sonder','Ryuki',5,0,'Season 2','Sonder'),
    (154, 'Darxy','Hazu',5,0,'Season 2','Darxy'),
    (155, 'LozKias','Algernon',5,4,'Season 2','LozKias'),
    (156, 'HolyCarp','Sett',5,1,'Season 2','HolyCarp'),
    (157, 'Finzy','Pikapi',5,4,'Season 2','Finzy'),
    (158, 'ETS','Polosaty',5,2,'Season 2','ETS'),
    (159, 'Lyonide','Graveryl',5,4,'Season 2','Lyonide'),
    (160, 'VileMuffin','Ventras',5,4,'Season 2','VileMuffin'),
    (161, 'Tadlos','SiloZen',5,0,'Season 2','Tadlos'),
    (162, 'Doktai','PanPan',5,1,'Season 2','Doktai'),
    (163, 'Zollith','Aby',5,0,'Season 2','Zollith'),
    (164, 'Baddy','Habaduba',10,3,'Season 2','Baddy'),
    (165, 'Valhanya','Jazair',5,0,'Season 2','Valhanya'),
    (166, 'Sonder','Finzy',5,2,'Season 2','Sonder'),
    (167, 'Habaduba','Lyonide',5,3,'Season 2','Habaduba'),
    (168, 'Aarpia','D3xus',10,5,'Season 2','Aarpia'),
    (169, 'Pikapi','Ryuki',5,4,'Season 2','Pikapi'),
    (170, 'Graveryl','Unicorn',5,1,'Season 2','Graveryl'),
    (171, 'Tadlos','TapiocaKing',5,2,'Season 2','Tadlos'),
    (172, 'Myloes','Sett',5,3,'Season 2','Myloes'),
    (173, 'Tadlos','Momotehk',5,0,'Season 2','Tadlos'),
    (174, 'Rosa','Zaydan',5,0,'Season 2','Rosa'),
    (175, 'WorldBranstar','Aby',5,2,'Season 2','WorldBranstar'),
    (176, 'Ceiwen','VileMuffin',5,1,'Season 2','Ceiwen'),
    (177, 'The Arpeggiator','Nickvold',5,0,'Season 2','The Arpeggiator'),
    (178, 'Stray','ETS',5,4,'Season 2','Stray'),
    (179, 'Hazu','Dzing',5,1,'Season 2','Hazu'),
    (180, 'Sams','Baddy',10,5,'Season 2','Sams'),
    (181, 'Polosaty','Vincent',5,4,'Season 2','Polosaty'),
    (182, 'Carriacou','Ol[d]cadan',5,3,'Season 2','Carriacou'),
    (183, 'Zanaken','MonkeyKing',5,2,'Season 2','Zanaken'),
    (184, 'Domitto','Andyroo',10,3,'Season 2','Domitto'),
    (185, 'LozKias','Lyonide',5,4,'Season 2','LozKias'),
    (186, 'Habaduba','VileMuffin',5,3,'Season 2','Habaduba'),
    (187, 'Baddy','Sett',10,2,'Season 2','Baddy'),
    (188, 'D3xus','Aelz',10,6,'Season 2','D3xus'),
    (189, 'Zephyrion','Kellerak',5,3,'Season 3','Zephyrion'),
    (190, 'WorldBranstar','Kusoge',5,0,'Season 3','WorldBranstar'),
    (191, 'Unicorn','Momotehk',5,3,'Season 3','Unicorn'),
    (192, 'D3xus','Ssylus',10,2,'Season 3','D3xus'),
    (193, 'Yaj-Ly','Tadlos',5,3,'Season 3','Yaj-Ly'),
    (194, 'Fotten','LozKias',5,1,'Season 3','Fotten'),
    (195, 'Jazair','Lyonide',5,4,'Season 3','Jazair'),
    (196, 'Ol[d]cadan','Vincent',5,2,'Season 3','Ol[d]cadan'),
    (197, 'Vegasvat','Miha',5,1,'Season 3','Vegasvat'),
    (198, 'MPhantasm','MonkeyKing',5,4,'Season 3','MPhantasm'),
    (199, 'Rufus','Spirit410',5,1,'Season 3','Rufus'),
    (200, 'Stray','Taokaka Meow',5,4,'Season 3','Stray'),
    (201, 'Darxy','Zollith',5,1,'Season 3','Darxy'),
    (202, 'Yin','DarthSeppius',10,3,'Season 3','Yin'),
    (203, 'The Arpeggiator','Kellerak',5,4,'Season 3','The Arpeggiator'),
    (204, 'Hazu','Afflatus Misery',5,2,'Season 3','Hazu'),
    (205, 'Fotten','Lyonide',5,1,'Season 3','Fotten'),
    (206, 'Ganondeurf','Domitto',10,0,'Season 3','Ganondeurf'),
    (207, 'Petronixman','Miha',5,3,'Season 3','Petronixman'),
    (208, 'Vincent','Momotehk',5,1,'Season 3','Vincent'),
    (209, 'Aelz','Rufus',10,6,'Season 3','Aelz'),
    (210, 'Drunky','Kusoge',5,3,'Season 3','Drunky'),
    (211, 'Taokaka Meow','Sekirei',5,1,'Season 3','Taokaka Meow'),
    (212, 'LozKias','VileMuffin',5,1,'Season 3','LozKias'),
    (213, 'Baddy','Myloes',5,1,'Season 3','Baddy'),
    (214, 'Yaj-Ly','Greywall',5,3,'Season 3','Yaj-Ly'),
    (215, 'Zephyrion','Polosaty',5,1,'Season 3','Zephyrion'),
    (216, 'WorldBranstar','Lyonide',5,2,'Season 3','WorldBranstar'),
    (217, 'Raziel','Ganondeurf',5,1,'Season 3','Raziel'),
    (218, 'Taokaka Meow','Iona Rose',5,1,'Season 3','Taokaka Meow'),
    (219, 'Kellerak','Unicorn',10,0,'Season 3','Kellerak'),
    (220, 'Habaduba','Fotten',10,6,'Season 3','Habaduba'),
    (221, 'Afflatus Misery','Tadlos',5,1,'Season 3','Afflatus Misery'),
    (222, 'Ventras','Ceiwen',5,4,'Season 3','Ventras'),
    (223, 'Ssylus','Baddy',5,1,'Season 3','Ssylus'),
    (224, 'Kusoge','Horken',5,2,'Season 3','Kusoge'),
    (225, 'Zephyrion','Yaj-Ly',5,2,'Season 3','Zephyrion'),
    (226, 'WorldBranstar','Fotten',5,1,'Season 3','WorldBranstar'),
    (227, 'Greywall','TapiocaKing',5,1,'Season 3','Greywall'),
    (228, 'Stray','Vincent',5,3,'Season 3','Stray'),
    (229, 'Taokaka Meow','Hazu',5,4,'Season 3','Taokaka Meow'),
    (230, 'MonkeyKing','Algernon',5,3,'Season 3','MonkeyKing'),
    (231, 'LozKias','Zanaken',5,0,'Season 3','LozKias'),
    (232, 'Carriacou','Horken',5,3,'Season 3','Carriacou'),
    (233, 'WorldBranstar','LozKias',5,2,'Season 3','WorldBranstar'),
    (234, 'Valhanya','VileMuffin',5,4,'Season 3','Valhanya'),
    (235, 'Sams','Ganondeurf',10,6,'Season 3','Sams'),
    (236, 'Tadlos','Greywall',5,4,'Season 3','Tadlos'),
    (237, 'Stray','Yaj-Ly',5,0,'Season 3','Stray'),
    (238, 'Zollith','Aby',5,4,'Season 3','Zollith'),
    (239, 'Darxy','Taokaka Meow',5,2,'Season 3','Darxy'),
    (240, 'Stray','TapiocaKing',5,0,'Season 3','Stray'),
    (241, 'Afflatus Misery','Ol[d]cadan',5,3,'Season 3','Afflatus Misery'),
    (242, 'Hazu','Lyonide',5,3,'Season 3','Hazu'),
    (243, 'Domitto','Spirit410',5,1,'Season 3','Domitto'),
    (244, 'Carriacou','Tadlos',5,0,'Season 3','Carriacou'),
    (245, 'Blade of Flame','Taokaka Meow',5,2,'Season 3','Blade of Flame'),
    (246, 'MonkeyKing','Valhanya',5,4,'Season 3','MonkeyKing'),
    (247, 'Ganondeurf','Neon',5,3,'Season 3','Ganondeurf'),
    (248, 'Horken','Momotehk',5,2,'Season 3','Horken'),
    (249, 'Aby','Lyonide',5,4,'Season 3','Aby'),
    (250, 'Taz','Zollith',5,4,'Season 3','Taz'),
    (251, 'Spirit410','WorldBranstar',10,4,'Season 3','Spirit410'),
    (252, 'MonkeyKing','Fotten',5,0,'Season 3','MonkeyKing'),
    (253, 'LozKias','WorldBranstar',5,0,'Season 3','LozKias'),
    (254, 'Ssylus','Ganondeurf',5,0,'Season 3','Ssylus'),
    (255, 'D3xus','Aelz',5,0,'Season 3','D3xus'),
    (257, 'Lyonide','Iona Rose',5,1,'Season 4','Lyonide'),
    (258, 'Stray','Aby',4,2,'Season 4','Stray'),
    (259, 'Zanaken','Fotten',5,4,'Season 4','Zanaken'),
    (260, 'Guilu','Sett',5,4,'Season 4','Guilu'),
    (261, 'The Arpeggiator','Momotehk',5,0,'Season 4','The Arpeggiator'),
    (262, 'Kellerak','polosaty',5,1,'Season 4','Kellerak'),
    (263, 'VileMuffin','Zephyrion',5,1,'Season 4','VileMuffin'),
    (264, 'Ventras','WorldBranstar',5,1,'Season 4','Ventras'),
    (265, 'Amancio Ortega','Jumpie',5,1,'Season 4','Amancio Ortega'),
    (266, 'Unicorn','Afflatus Misery',5,4,'Season 4','Unicorn'),
    (267, 'Hazu','Stray',5,0,'Season 4','Hazu'),
    (268, 'Darxy','Valhanya',5,4,'Season 4','Darxy'),
    (269, 'MPhantasm','The Arpeggiator',5,3,'Season 4','MPhantasm'),
    (270, 'Tadlos','Pikapi',5,3,'Season 4','Tadlos'),
    (271, 'Fotten','Taokaka Meow',5,3,'Season 4','Fotten'),
    (272, 'Skyll','D3xus',10,5,'Season 4','Skyll'),
    (273, 'Kellerak','Drunky',5,2,'Season 4','Kellerak'),
    (274, 'Lyonide','Cpt-GI',5,2,'Season 4','Lyonide'),
    (275, 'Guilu','LozKias',5,2,'Season 4','Guilu'),
    (276, 'Momotehk','polosaty',5,4,'Season 4','Momotehk'),
    (277, 'Zollith','Zephyrion',5,4,'Season 4','Zollith'),
    (278, 'Sett','Ventras',5,2,'Season 4','Sett'),
    (279, 'Habaduba','DarthSeppius',10,2,'Season 4','Habaduba'),
    (280, 'Amancio Ortega','Tadlos',5,0,'Season 4','Amancio Ortega'),
    (281, 'Zollith','Lyonide',5,2,'Season 4','Zollith'),
    (282, 'Hazu','Jazair',5,2,'Season 4','Hazu'),
    (283, 'D3xus','Aarpia',10,3,'Season 4','D3xus'),
    (284, 'Momotehk','Miha Senju',5,3,'Season 4','Momotehk'),
    (285, 'Kellerak','Aby',5,1,'Season 4','Kellerak'),
    (286, 'Taokaka Meow','Graveryl',5,2,'Season 4','Taokaka Meow'),
    (287, 'Domitto','Baddy',5,3,'Season 4','Domitto'),
    (288, 'Fotten','Hazu',5,4,'Season 4','Fotten'),
    (289, 'Sett','Guilu',10,9,'Season 4','Sett'),
    (290, 'Aelz','Ssylus',10,2,'Season 4','Aelz'),
    (291, 'Jumpie','REKORDER',5,0,'Season 4','Jumpie'),
    (292, 'Amancio Ortega','Afflatus Misery',5,3,'Season 4','Amancio Ortega'),
    (293, 'Taokaka Meow','Jazair',5,2,'Season 4','Taokaka Meow'),
    (294, 'Blade of Flame','Ventras',4,1,'Season 4','Blade of Flame'),
    (295, 'Hamidumi','Miha Senju',5,1,'Season 4','Hamidumi'),
    (296, 'Greywall','polosaty',5,0,'Season 4','Greywall'),
    (297, 'Cpt-GI','Momotehk',5,1,'Season 4','Cpt-GI'),
    (298, 'Lyonide','Aby',5,1,'Season 4','Lyonide'),
    (299, 'Habaduba','Spirit410',5,2,'Season 4','Habaduba'),
    (300, 'Nins','REKORDER',5,1,'Season 4','Nins'),
    (301, 'Lyonide','Jazair',5,2,'Season 4','Lyonide'),
    (302, 'Fotten','Fanlee Jr',5,4,'Season 4','Fotten'),
    (303, 'Ganondeurf','Aarpia',10,9,'Season 4','Ganondeurf'),
    (304, 'Afflatus Misery','Momotehk',5,1,'Season 4','Afflatus Misery'),
    (305, 'SHeF-87','Zephyrion',5,2,'Season 4','SHeF-87'),
    (306, 'Kellerak','Sekirei',5,4,'Season 4','Kellerak'),
    (307, 'Guilu','Darxy',10,2,'Season 4','Guilu'),
    (308, 'Aby','dopppa',5,1,'Season 4','Aby'),
    (309, 'Zollith','SpartanTigra',5,4,'Season 4','Zollith'),
    (310, 'Sett','Spirit410',5,1,'Season 4','Sett'),
    (311, 'Mental','Tadlos',5,4,'Season 4','Mental'),
    (312, 'VileMuffin','Taokaka Meow',5,0,'Season 4','VileMuffin'),
    (313, 'LozKias','MonkeyKing',5,2,'Season 4','LozKias'),
    (314, 'Yin','Domitto',5,2,'Season 4','Yin'),
    (315, 'Nins','Jumpie',5,4,'Season 4','Nins'),
    (316, 'Deyan87','Faultroll',5,4,'Season 4','Deyan87'),
    (317, 'Fanlee Jr','LEV77',5,1,'Season 4','Fanlee Jr'),
    (318, 'Ventras','Hazu',5,2,'Season 4','Ventras'),
    (319, 'Afflatus Misery','Mental',5,3,'Season 4','Afflatus Misery'),
    (320, 'Lyonide','Graveryl',5,2,'Season 4','Lyonide'),
    (321, 'Zollith','Fotten',5,2,'Season 4','Zollith'),
    (322, 'Raziel','Ssylus',5,2,'Season 4','Raziel'),
    (323, 'PanPan','Tadlos',5,4,'Season 4','PanPan'),
    (324, 'Valhanya','Billflop',5,3,'Season 4','Valhanya'),
    (325, 'Kellerak','Taokaka Meow',5,4,'Season 4','Kellerak'),
    (326, 'LozKias','Blade of Flame',5,1,'Season 4','LozKias'),
    (327, 'Tadlos','Pikapi',5,0,'Season 4','Tadlos'),
    (328, 'Amancio Ortega','Kusoge',5,0,'Season 4','Amancio Ortega'),
    (329, 'Billflop','Afflatus Misery',5,1,'Season 4','Billflop'),
    (330, 'Sekirei','Nashley',5,0,'Season 4','Sekirei'),
    (331, 'Hazu','WorldBranstar',5,0,'Season 4','Hazu'),
    (332, 'Guilu','Sett',10,2,'Season 4','Guilu'),
    (333, 'Yin','Ganondeurf',5,0,'Season 4','Yin'),
    (334, 'Skyll','Aelz',10,3,'Season 4','Skyll'),
    (335, 'Afflatus Misery','Unicorn',5,4,'Season 5','Afflatus Misery'),
    (336, 'Hazu','VileMuffin',5,2,'Season 5','Hazu'),
    (337, 'D3xus','DarthSeppius',5,1,'Season 5','D3xus'),
    (338, 'Aby','Iona Rose',5,1,'Season 5','Aby'),
    (339, 'Lyonide','Kellerak',5,3,'Season 5','Lyonide'),
    (340, 'Domitto','Ganondeurf',5,4,'Season 5','Domitto'),
    (341, 'Sonder','Horken',5,2,'Season 5','Sonder'),
    (342, 'Freemard','SHeF-87',5,0,'Season 5','Freemard'),
    (343, 'Taokaka Meow','Aby',5,3,'Season 5','Taokaka Meow'),
    (344, 'WorldBranstar','Kellerak',5,0,'Season 5','WorldBranstar'),
    (345, 'LozKias','Lyonide',5,3,'Season 5','LozKias'),
    (346, 'Tadlos','Jumpie',5,2,'Season 5','Tadlos'),
    (347, 'Rosa','Sekirei',5,2,'Season 5','Rosa'),
    (348, 'Fotten','Darxy',5,0,'Season 5','Fotten'),
    (349, 'DarthSeppius','Habaduba',5,4,'Season 5','DarthSeppius'),
    (350, 'D3xus','Ssylus',5,2,'Season 5','D3xus'),
    (351, 'Gaspar','Tadlos',5,0,'Season 5','Gaspar'),
    (352, 'Aby','Afflatus Misery',5,3,'Season 5','Aby'),
    (353, 'Fotten','Mental',5,3,'Season 5','Fotten'),
    (354, 'WorldBranstar','SpartanTigra',5,3,'Season 5','WorldBranstar'),
    (355, 'Sett','Lyonide',5,2,'Season 5','Sett'),
    (356, 'The Arpeggiator','Jumpie',5,0,'Season 5','The Arpeggiator'),
    (357, 'Freemard','Zollith',5,1,'Season 5','Freemard'),
    (358, 'Ssylus','Habaduba',5,0,'Season 5','Ssylus'),
    (359, 'Tadlos','TapiocaKing',5,1,'Season 5','Tadlos'),
    (360, 'Stray','The Arpeggiator',5,4,'Season 5','Stray'),
    (361, 'Kellerak','SpartanTigra',5,4,'Season 5','Kellerak'),
    (362, 'Ganondeurf','DarthSeppius',5,2,'Season 5','Ganondeurf'),
    (363, 'Junky','SiloZen',5,2,'Season 5','Junky'),
    (364, 'Jumpie','X-Ray',5,2,'Season 5','Jumpie'),
    (365, 'Sonder','Patrick',5,2,'Season 5','Sonder'),
    (366, 'Freemard','Fotten',5,2,'Season 5','Freemard'),
    (367, 'Ssylus','Blade of Flame',5,2,'Season 5','Ssylus'),
    (368, 'Sonder','SomethingRefined',5,1,'Season 5','Sonder'),
    (369, 'Mental','WorldBranstar',5,4,'Season 5','Mental'),
    (370, 'Sekirei','SpartanTigra',5,1,'Season 5','Sekirei'),
    (371, 'Ganondeurf','Ssylus',5,4,'Season 5','Ganondeurf'),
    (372, 'Patrick','Volty',5,3,'Season 5','Patrick'),
    (373, 'ZER0','Tadlos',5,3,'Season 5','ZER0'),
    (374, 'Fotten','Lyonide',5,4,'Season 5','Fotten'),
    (375, 'Valhanya','Kellerak',5,1,'Season 5','Valhanya'),
    (376, 'Freemard','Sett',5,3,'Season 5','Freemard'),
    (377, 'X-Ray','SomethingRefined',5,4,'Season 5','X-Ray'),
    (378, 'Momotehk','Jumpie',5,4,'Season 5','Momotehk'),
    (379, 'Patrick','Frieden',5,1,'Season 5','Patrick'),
    (380, 'VileMuffin','Taokaka Meow',5,1,'Season 5','VileMuffin'),
    (381, 'Ganondeurf','Baddy',5,1,'Season 5','Ganondeurf'),
    (382, 'Mental','Kellerak',5,4,'Season 5','Mental'),
    (383, 'Tadlos','X-Ray',5,1,'Season 5','Tadlos'),
    (384, 'SomethingRefined','Volty',5,4,'Season 5','SomethingRefined'),
    (385, 'Fotten','VileMuffin',5,4,'Season 5','Fotten'),
    (386, 'Aby','SpartanTigra',5,0,'Season 5','Aby'),
    (387, 'Jumpie','Junky',5,0,'Season 5','Jumpie'),
    (388, 'Yin','Ssylus',5,1,'Season 5','Yin'),
    (389, 'SomethingRefined','Horken',5,1,'Season 5','SomethingRefined'),
    (390, 'Lars','FateKuru',5,0,'Season 5','Lars'),
    (391, 'Volty','Jumpie',5,2,'Season 5','Volty'),
    (392, 'Lyonide','LEV77',5,2,'Season 5','Lyonide'),
    (393, 'Mental','Afflatus Misery',5,3,'Season 5','Mental'),
    (394, 'Kellerak','The Arpeggiator',5,1,'Season 5','Kellerak'),
    (395, 'Momotehk','X-Ray',5,3,'Season 5','Momotehk'),
    (396, 'Sett','Lyonide',5,3,'Season 5','Sett'),
    (397, 'WorldBranstar','Necrologen',5,3,'Season 5','WorldBranstar'),
    (398, 'Zollith','Aby',5,2,'Season 5','Zollith'),
    (399, 'Gaspar','Jumpie',5,1,'Season 5','Gaspar'),
    (400, 'X-Ray','Junky',5,3,'Season 5','X-Ray'),
    (401, 'Habaduba','Ganondeurf',5,3,'Season 5','Habaduba'),
    (402, 'Rosa','Raziel',5,4,'Season 5','Rosa'),
    (403, 'WorldBranstar','Patrick',5,3,'Season 5','WorldBranstar'),
    (404, 'Kellerak','SpartanTigra',5,2,'Season 5','Kellerak'),
    (405, 'Volty','X-Ray',5,2,'Season 5','Volty'),
    (406, 'LEV77','Fotten',5,4,'Season 5','LEV77'),
    (407, 'Ozhora','Jumpie',5,4,'Season 5','Ozhora'),
    (408, 'Freemard','Lyonide',5,2,'Season 5','Freemard'),
    (409, 'Kellerak','JabberJayJay',5,3,'Season 5','Kellerak'),
    (410, 'Scarlet','X-Ray',5,2,'Season 5','Scarlet'),
    (411, 'The Arpeggiator','Momotehk',5,2,'Season 5','The Arpeggiator'),
    (412, 'Ssylus','DarthSeppius',5,1,'Season 5','Ssylus'),
    (413, 'Freemard','LozKias',5,2,'Season 5','Freemard'),
    (414, 'Mental','The Arpeggiator',5,3,'Season 5','Mental'),
    (415, 'Scarlet','AutobahnAlpha',5,1,'Season 5','Scarlet'),
    (416, 'WorldBranstar','JabberJayJay',5,4,'Season 5','WorldBranstar'),
    (417, 'Tadlos','Afflatus Misery',5,4,'Season 5','Tadlos'),
    (418, 'MonkeyKing','X-Ray',5,3,'Season 5','MonkeyKing'),
    (419, 'Ganondeurf','WorldBranstar',10,7,'Season 5','Ganondeurf'),
    (420, 'Ssylus','Noobycide',5,3,'Season 5','Ssylus'),
    (421, 'Freemard','Aby',5,1,'Season 5','Freemard'),
    (422, 'Lyonide','Scarlet',5,4,'Season 5','Lyonide'),
    (423, 'Fanlee Jr','DarthSeppius',10,3,'Season 5','Fanlee Jr'),
    (424, 'Scarlet','Afflatus Misery',5,0,'Season 5','Scarlet'),
    (425, 'Ssylus','Fotten',10,2,'Season 5','Ssylus'),
    (426, 'Zollith','Jumpie',5,1,'Season 5','Zollith'),
    (427, 'Momotehk','Junky',5,0,'Season 5','Momotehk'),
    (428, 'Ssylus','WorldBranstar',5,1,'Season 5','Ssylus'),
    (429, 'DarthSeppius','MonkeyKing',5,3,'Season 5','DarthSeppius'),
    (430, 'Scarlet','Nashley',5,1,'Season 5','Scarlet'),
    (431, 'Aby','Afflatus Misery',10,6,'Season 5','Aby'),
    (432, 'Afflatus Misery','Patrick',10,9,'Season 5','Afflatus Misery'),
    (433, 'SomethingRefined','Tadlos',5,0,'Season 5','SomethingRefined'),
    (434, 'Rosa','Lyonide',10,0,'Season 5','Rosa'),
    (435, 'Scarlet','Tadlos',5,1,'Season 5','Scarlet'),
    (436, 'Scarlet','DarthSeppius',5,4,'Season 5','Scarlet'),
    (437, 'SomethingRefined','Afflatus Misery',5,3,'Season 5','SomethingRefined'),
    (438, 'Tadlos','Samurai',5,0,'Season 5','Tadlos'),
    (439, 'Jumpie','Metabee',5,2,'Season 5','Jumpie'),
    (440, 'WorldBranstar','Rosa',5,3,'Season 5','WorldBranstar'),
    (441, 'Freemard','Sett',5,1,'Season 5','Freemard'),
    (442, 'Kellerak','Zollith',5,1,'Season 5','Kellerak'),
    (443, 'X-Ray','TotemGenbu',5,2,'Season 5','X-Ray'),
    (444, 'Athena','DarthSeppius',5,2,'Season 5','Athena'),
    (445, 'Taokaka Meow','Gaspar',5,3,'Season 5','Taokaka Meow'),
    (446, 'Momotehk','Tadlos',5,1,'Season 5','Momotehk'),
    (447, 'X-Ray','Samurai',5,0,'Season 5','X-Ray'),
    (448, 'Aby','Baddy',5,2,'Season 5','Aby'),
    (449, 'Mental','Jumpie',5,3,'Season 5','Mental'),
    (450, 'Pikapi','TotemGenbu',5,4,'Season 5','Pikapi'),
    (451, 'Ganondeurf','Athena',5,4,'Season 5','Ganondeurf'),
    (452, 'Gaspar','Jumpie',5,0,'Season 5','Gaspar'),
    (453, 'Mental','Aby',5,4,'Season 5','Mental'),
    (454, 'Hajin','Momotehk',5,4,'Season 5','Hajin'),
    (455, 'Freemard','DarthSeppius',5,2,'Season 5','Freemard'),
    (456, 'Taokaka Meow','The Arpeggiator',5,2,'Season 5','Taokaka Meow'),
    (457, 'TotemGenbu','Kellerak',5,3,'Season 5','TotemGenbu'),
    (458, 'Horken','X-Ray',5,0,'Season 5','Horken'),
    (459, 'Hajin','Pikapi',5,1,'Season 5','Hajin'),
    (460, 'Jumpie','Tadlos',5,4,'Season 5','Jumpie'),
    (461, 'X-Ray','Goatreich',5,2,'Season 5','X-Ray');

  -- Insert unique events
  INSERT INTO events(title, event_date)
  SELECT DISTINCT event, NOW()
    FROM seeddata
  WHERE 
    NOT EXISTS(
      SELECT 1
      FROM events AS E
      WHERE E.title = seeddata.event
    )
  ORDER BY event;

  -- Insert unique players
  INSERT INTO players(name)
  SELECT DISTINCT name
    FROM (
      SELECT player1 as name FROM seeddata
      UNION SELECT player2 FROM seeddata
    ) AS T
  WHERE 
    NOT EXISTS(
      SELECT 1
      FROM players AS P
      WHERE P.name = T.name
    );

  -- Insert match data
  INSERT INTO matches(
    player1_id, player1_score,
    player2_id, player2_score, 
    winner_id, event_id, 
    match_order
  )
  SELECT
    P1.id, S.player1score,
    P2.id, S.player2score,
    W.id,
    E.id,
    S.row_index
  FROM seeddata as S
  INNER JOIN players AS P1 ON P1.name = S.player1
  INNER JOIN players AS P2 ON P2.name = S.player2
  INNER JOIN players AS W ON W.name = S.winner
  INNER JOIN events AS E ON E.title = S.event
  ORDER BY S.row_index;

  DROP TABLE seeddata;


  UPDATE matches
  SET vod_link = 'https://www.youtube.com/shorts/IZMaHVVIObs';

  UPDATE events
  SET vod_link = 'https://youtu.be/1sFbLppuhhs?si=JUlABkFdrF5MYYvy';
END $$;
