-- Seed data generated from sampleData.csv
-- Total matches: 455
-- Total events: 5

DO $$
BEGIN
  DROP TABLE IF EXISTS seeddata;
  CREATE TEMP TABLE seeddata(
    player1 varchar(128),
    player2 varchar(128),
    player1score INT,
    player2score INT,
    event varchar(128),
    winner varchar(128)
  );

  INSERT INTO seeddata (player1, player2, player1score, player2score, event, winner) 
  VALUES
    ('Freemard','Aby',5,1,'Season 5','Freemard'),
    ('Mental','Aby',5,4,'Season 5','Mental'),
    ('TaokakaMeow','Aby',5,3,'Season 5','TaokakaMeow'),
    ('Zollith','Aby',5,2,'Season 5','Zollith'),
    ('Aby','Afflatus Misery',10,6,'Season 5','Aby'),
    ('Aby','Afflatus Misery',5,3,'Season 5','Aby'),
    ('Mental','Afflatus Misery',5,3,'Season 5','Mental'),
    ('Scarlet','Afflatus Misery',5,0,'Season 5','Scarlet'),
    ('SomethingRefined','Afflatus Misery',5,3,'Season 5','SomethingRefined'),
    ('Tadlos','Afflatus Misery',5,4,'Season 5','Tadlos'),
    ('Ganondeurf','Athena',5,4,'Season 5','Ganondeurf'),
    ('Scarlet','AutobahnAlpha',5,1,'Season 5','Scarlet'),
    ('Aby','Baddy',5,2,'Season 5','Aby'),
    ('Ganondeurf','Baddy',5,1,'Season 5','Ganondeurf'),
    ('Ssylus','Blade of Flame',5,2,'Season 5','Ssylus'),
    ('Athena','DarthSeppius',5,2,'Season 5','Athena'),
    ('D3xus','DarthSeppius',5,1,'Season 5','D3xus'),
    ('Fanlee','DarthSeppius',10,3,'Season 5','Fanlee'),
    ('Freemard','DarthSeppius',5,2,'Season 5','Freemard'),
    ('Ganondeurf','DarthSeppius',5,2,'Season 5','Ganondeurf'),
    ('Scarlet','DarthSeppius',5,4,'Season 5','Scarlet'),
    ('Ssylus','DarthSeppius',5,1,'Season 5','Ssylus'),
    ('Fotten','Darxy',5,0,'Season 5','Fotten'),
    ('Lars','FateKuru',5,0,'Season 5','Lars'),
    ('Freemard','Fotten',5,2,'Season 5','Freemard'),
    ('Lev','Fotten',5,4,'Season 5','Lev'),
    ('Patrick','Frieden',5,1,'Season 5','Patrick'),
    ('Habaduba','Ganondeurf',5,3,'Season 5','Habaduba'),
    ('Domitto','Ganondeurf',5,4,'Season 5','Domitto'),
    ('TaokakaMeow','GasparSC',5,3,'Season 5','TaokakaMeow'),
    ('X-Ray','Goatreich',5,2,'Season 5','X-Ray'),
    ('DarthSeppius','Habaduba',5,4,'Season 5','DarthSeppius'),
    ('Ssylus','Habaduba',5,0,'Season 5','Ssylus'),
    ('SomethingRefined','Horken',5,1,'Season 5','SomethingRefined'),
    ('Sonder','Horken',5,2,'Season 5','Sonder'),
    ('Ssylus','Fotten',10,2,'Season 5','Ssylus'),
    ('Aby','Iona Rose',5,1,'Season 5','Aby'),
    ('Kellerak','JabberJayjay',5,3,'Season 5','Kellerak'),
    ('WorldBranstar','Jabberjayjay',5,4,'Season 5','WorldBranstar'),
    ('GasparSC','Jumpie',5,0,'Season 5','GasparSC'),
    ('GasparSC','Jumpie',5,1,'Season 5','GasparSC'),
    ('Mental','Jumpie',5,3,'Season 5','Mental'),
    ('Mo[M]otehk','Jumpie',5,4,'Season 5','Mo[M]otehk'),
    ('Ozhora','Jumpie',5,4,'Season 5','Ozhora'),
    ('Tadlos','Jumpie',5,2,'Season 5','Tadlos'),
    ('The Arpeggiator','Jumpie',5,0,'Season 5','The Arpeggiator'),
    ('Volty','Jumpie',5,2,'Season 5','Volty'),
    ('Zollith','Jumpie',5,1,'Season 5','Zollith'),
    ('Jumpie','Junky',5,0,'Season 5','Jumpie'),
    ('Momo','Junky',5,0,'Season 5','Momo'),
    ('X-Ray','Junky',5,3,'Season 5','X-Ray'),
    ('Lyonide','Kellerak',5,3,'Season 5','Lyonide'),
    ('Mental','Kellerak',5,4,'Season 5','Mental'),
    ('TotemGenbu','Kellerak',5,3,'Season 5','TotemGenbu'),
    ('Valhanya','Kellerak',5,1,'Season 5','Valhanya'),
    ('WorldBranstar','Kellerak',5,0,'Season 5','WorldBranstar'),
    ('Lyonide','LEV77',5,2,'Season 5','Lyonide'),
    ('Freemard','Loz Kias',5,2,'Season 5','Freemard'),
    ('Fotten','Lyonide',5,4,'Season 5','Fotten'),
    ('Freemard','Lyonide',5,2,'Season 5','Freemard'),
    ('Loz Kias','Lyonide',5,3,'Season 5','Loz Kias'),
    ('Rosa','Lyonide',10,0,'Season 5','Rosa'),
    ('Sett','Lyonide',5,3,'Season 5','Sett'),
    ('Sett','Lyonide',5,2,'Season 5','Sett'),
    ('Fotten','Mental',5,3,'Season 5','Fotten'),
    ('Jumpie','Metabee',5,2,'Season 5','Jumpie'),
    ('Hajin','Momotehk',5,4,'Season 5','Hajin'),
    ('The Arpeggiator','Momotehk',5,2,'Season 5','The Arpeggiator'),
    ('DarthSeppius','MonkeyKing',5,3,'Season 5','DarthSeppius'),
    ('Scarlet','Nashley',5,1,'Season 5','Scarlet'),
    ('WorldBranstar','Necrologen',5,3,'Season 5','WorldBranstar'),
    ('Ssylus','Noobycide',5,3,'Season 5','Ssylus'),
    ('Afflatus Misery','Patrick',10,9,'Season 5','Afflatus Misery'),
    ('Sonder','Patrick',5,2,'Season 5','Sonder'),
    ('WorldBranstar','Patrick',5,3,'Season 5','WorldBranstar'),
    ('Rosa','Raziel',5,4,'Season 5','Rosa'),
    ('WorldBranstar','Rosa',5,3,'Season 5','WorldBranstar'),
    ('Tadlos','Samurai',5,0,'Season 5','Tadlos'),
    ('X-Ray','Samurai',5,0,'Season 5','X-Ray'),
    ('Lyonide','Scarlet',5,4,'Season 5','Lyonide'),
    ('Rosa','Sekirei',5,2,'Season 5','Rosa'),
    ('Freemard','Sett',5,1,'Season 5','Freemard'),
    ('Freemard','Sett',5,3,'Season 5','Freemard'),
    ('Freemard','SHeF-87',5,0,'Season 5','Freemard'),
    ('Junky','SiloZen',5,2,'Season 5','Junky'),
    ('Sonder','SomethingRefined',5,1,'Season 5','Sonder'),
    ('X-Ray','SomethingRefined',5,4,'Season 5','X-Ray'),
    ('Kellerak','SpartanTigra',5,2,'Season 5','Kellerak'),
    ('Aby','SpartanTigra',5,0,'Season 5','Aby'),
    ('Kellerak','SpartanTigra',5,4,'Season 5','Kellerak'),
    ('Sekirei','SpartanTigra',5,1,'Season 5','Sekirei'),
    ('WorldBranstar','SpartanTigra',5,3,'Season 5','WorldBranstar'),
    ('D3xus','Ssylus',5,2,'Season 5','D3xus'),
    ('Ganondeurf','Ssylus',5,4,'Season 5','Ganondeurf'),
    ('Yin','Ssylus',5,1,'Season 5','Yin'),
    ('GasparSC','Tadlos',5,0,'Season 5','GasparSC'),
    ('Jumpie','Tadlos',5,4,'Season 5','Jumpie'),
    ('Momo','Tadlos',5,1,'Season 5','Momo'),
    ('Scarlet','Tadlos',5,1,'Season 5','Scarlet'),
    ('SomethingRefined','Tadlos',5,0,'Season 5','SomethingRefined'),
    ('ZER0','Tadlos',5,3,'Season 5','ZER0'),
    ('VileMuffin','TaokakaMeow',5,1,'Season 5','VileMuffin'),
    ('Tadlos','TapiocaKing',5,1,'Season 5','Tadlos'),
    ('Mental','The Arpeggiator',5,3,'Season 5','Mental'),
    ('Stray','The Arpeggiator',5,4,'Season 5','Stray'),
    ('TaokakaMeow','The Arpeggiator',5,2,'Season 5','TaokakaMeow'),
    ('Kellerak','The Arpeggiator',5,1,'Season 5','Kellerak'),
    ('X-Ray','TotemGenbu',5,2,'Season 5','X-Ray'),
    ('Pikapi','TotemGenbu',5,4,'Season 5','Pikapi'),
    ('Afflatus Misery','Unicorn',5,4,'Season 5','Afflatus Misery'),
    ('Hazu','VileMuffin',5,2,'Season 5','Hazu'),
    ('Fotten','VileMuffin',5,4,'Season 5','Fotten'),
    ('Patrick','Volty',5,3,'Season 5','Patrick'),
    ('SomethingRefined','Volty',5,4,'Season 5','SomethingRefined'),
    ('Ganondeurf','WorldBranstar',10,7,'Season 5','Ganondeurf'),
    ('Mental','WorldBranstar',5,4,'Season 5','Mental'),
    ('Ssylus','WorldBranstar',5,1,'Season 5','Ssylus'),
    ('Horken','X-Ray',5,0,'Season 5','Horken'),
    ('Jumpie','X-Ray',5,2,'Season 5','Jumpie'),
    ('Momo','X-Ray',5,3,'Season 5','Momo'),
    ('MonkeyKing','X-Ray',5,3,'Season 5','MonkeyKing'),
    ('Scarlet','X-Ray',5,2,'Season 5','Scarlet'),
    ('Tadlos','X-Ray',5,1,'Season 5','Tadlos'),
    ('Volty','X-Ray',5,2,'Season 5','Volty'),
    ('Hajin','Yangin',5,1,'Season 5','Hajin'),
    ('Freemard','Zollith',5,1,'Season 5','Freemard'),
    ('Kellerak','Zollith',5,1,'Season 5','Kellerak'),
    ('D3xus','Aarpia',10,3,'Season 4','D3xus'),
    ('Ganondeurf','Aarpia',10,9,'Season 4','Ganondeurf'),
    ('Stray','Aby',4,2,'Season 4','Stray'),
    ('Kellerak','Aby',5,1,'Season 4','Kellerak'),
    ('Lyonide','Aby',5,1,'Season 4','Lyonide'),
    ('Skyll','Aelz',10,3,'Season 4','Skyll'),
    ('Amancio Ortega','Afflatus Misery',5,3,'Season 4','Amancio Ortega'),
    ('Billflop','Afflatus Misery',5,1,'Season 4','Billflop'),
    ('Unicorn','Afflatus Misery',5,4,'Season 4','Unicorn'),
    ('Domitto','Baddy',5,3,'Season 4','Domitto'),
    ('Valhanya','Billflop',5,3,'Season 4','Valhanya'),
    ('Loz Kias','Blade of Flame',5,1,'Season 4','Loz Kias'),
    ('Lyonide','Cpt-GI',5,2,'Season 4','Lyonide'),
    ('Skyll','D3xus',10,5,'Season 4','Skyll'),
    ('Habaduba','DarthSeppius',10,2,'Season 4','Habaduba'),
    ('Guilu','Darxy',10,2,'Season 4','Guilu'),
    ('Yin','Domitto',5,2,'Season 4','Yin'),
    ('Aby','dopppa',5,1,'Season 4','Aby'),
    ('Kellerak','Drunky',5,2,'Season 4','Kellerak'),
    ('Fotten','Fanlee Jr',5,4,'Season 4','Fotten'),
    ('Deyan87','Faultroll',5,4,'Season 4','Deyan87'),
    ('Zanaken','Fotten',5,4,'Season 4','Zanaken'),
    ('Zollith','Fotten',5,2,'Season 4','Zollith'),
    ('Yin','Ganondeurf',5,0,'Season 4','Yin'),
    ('Lyonide','Graveryl',5,2,'Season 4','Lyonide'),
    ('TaokakaMeow','Graveryl',5,2,'Season 4','TaokakaMeow'),
    ('Sett','Guilu',10,9,'Season 4','Sett'),
    ('Fotten','Hazu',5,4,'Season 4','Fotten'),
    ('Ventras','Hazu',5,2,'Season 4','Ventras'),
    ('Lyonide','Iona Rose',5,1,'Season 4','Lyonide'),
    ('Hazu','Jazair',5,2,'Season 4','Hazu'),
    ('Lyonide','Jazair',5,2,'Season 4','Lyonide'),
    ('TaokakaMeow','Jazair',5,2,'Season 4','TaokakaMeow'),
    ('Amancio Ortega','Jumpie',5,1,'Season 4','Amancio Ortega'),
    ('nins','Jumpie',5,4,'Season 4','nins'),
    ('Amancio Ortega','Kusoge',5,0,'Season 4','Amancio Ortega'),
    ('Fanlee Jr','LEV77',5,1,'Season 4','Fanlee Jr'),
    ('Guilu','Loz Kias',5,2,'Season 4','Guilu'),
    ('Zollith','Lyonide',5,2,'Season 4','Zollith'),
    ('Afflatus Misery','Mental',5,3,'Season 4','Afflatus Misery'),
    ('Hamidumi','Miha Senju',5,1,'Season 4','Hamidumi'),
    ('Mo[M]otehk','Miha Senju',5,3,'Season 4','Mo[M]otehk'),
    ('Afflatus Misery','Momotehk',5,1,'Season 4','Afflatus Misery'),
    ('Cpt-GI','Momotehk',5,1,'Season 4','Cpt-GI'),
    ('The Arpeggiator','Momotehk',5,0,'Season 4','The Arpeggiator'),
    ('Loz Kias','MonkeyKing',5,2,'Season 4','Loz Kias'),
    ('Sekirei','Nashley',5,0,'Season 4','Sekirei'),
    ('Tadlos','Pikapi',5,0,'Season 4','Tadlos'),
    ('Tadlos','Pikapi',5,3,'Season 4','Tadlos'),
    ('Greywall','Polosaty',5,0,'Season 4','Greywall'),
    ('Kellerak','Polosaty',5,1,'Season 4','Kellerak'),
    ('Mo[M]otehk','Polosaty',5,4,'Season 4','Mo[M]otehk'),
    ('Jumpie','REKORDER',5,0,'Season 4','Jumpie'),
    ('nins','REKORDER',5,1,'Season 4','nins'),
    ('Kellerak','Sekirei',5,4,'Season 4','Kellerak'),
    ('Guilu','Sett',10,2,'Season 4','Guilu'),
    ('Guilu','Sett',5,4,'Season 4','Guilu'),
    ('Zollith','SpartanTigra',5,4,'Season 4','Zollith'),
    ('Habaduba','Spirit410',5,2,'Season 4','Habaduba'),
    ('Sett','Spirit410',5,1,'Season 4','Sett'),
    ('Aelz','Ssylus',10,2,'Season 4','Aelz'),
    ('Raziel','Ssylus',5,2,'Season 4','Raziel'),
    ('Hazu','Stray',5,0,'Season 4','Hazu'),
    ('Amancio Ortega','Tadlos',5,0,'Season 4','Amancio Ortega'),
    ('Mental','Tadlos',5,4,'Season 4','Mental'),
    ('PanPan','Tadlos',5,4,'Season 4','PanPan'),
    ('Fotten','TaokakaMeow',5,3,'Season 4','Fotten'),
    ('Kellerak','TaokakaMeow',5,4,'Season 4','Kellerak'),
    ('VileMuffin','TaokakaMeow',5,0,'Season 4','VileMuffin'),
    ('MPhantasm','The Arpeggiator',5,3,'Season 4','MPhantasm'),
    ('Darxy','Valhanya',5,4,'Season 4','Darxy'),
    ('Blade of Flame','Ventras',4,1,'Season 4','Blade of Flame'),
    ('Sett','Ventras',5,2,'Season 4','Sett'),
    ('Hazu','WorldBranstar',5,0,'Season 4','Hazu'),
    ('Ventras','WorldBranstar',5,1,'Season 4','Ventras'),
    ('SHeF-87','Zephyrion',5,2,'Season 4','SHeF-87'),
    ('VileMuffin','Zephyrion',5,1,'Season 4','VileMuffin'),
    ('Zollith','Zephyrion',5,4,'Season 4','Zollith'),
    ('Zollith','Aby',5,4,'Season 3','Zollith'),
    ('Hazu','Afflatus Misery',5,2,'Season 3','Hazu'),
    ('MonkeyKing','Algernon',5,3,'Season 3','MonkeyKing'),
    ('Ssylus','Baddy',5,1,'Season 3','Ssylus'),
    ('Ventras','Ceiwen',5,4,'Season 3','Ventras'),
    ('Yin','DarthSeppius',10,3,'Season 3','Yin'),
    ('Ganondeurf','Domitto',10,0,'Season 3','Ganondeurf'),
    ('Habaduba','Fotten',10,6,'Season 3','Habaduba'),
    ('WorldBranstar','Fotten',5,1,'Season 3','WorldBranstar'),
    ('Raziel','Ganondeurf',5,1,'Season 3','Raziel'),
    ('Sams','Ganondeurf',10,6,'Season 3','Sams'),
    ('Tadlos','Greywall',5,4,'Season 3','Tadlos'),
    ('Yaj-Ly','Greywall',5,3,'Season 3','Yaj-Ly'),
    ('TaokakaMeow','Hazu',5,4,'Season 3','TaokakaMeow'),
    ('carriacou','Horken',5,3,'Season 3','carriacou'),
    ('Kusoge','Horken',5,2,'Season 3','Kusoge'),
    ('TaokakaMeow','Iona Rose',5,1,'Season 3','TaokakaMeow'),
    ('The Arpeggiator','Kellerak',5,4,'Season 3','The Arpeggiator'),
    ('Zephyrion','Kellerak',5,3,'Season 3','Zephyrion'),
    ('Drunky','Kusoge',5,3,'Season 3','Drunky'),
    ('WorldBranstar','Kusoge',5,0,'Season 3','WorldBranstar'),
    ('Fotten','Loz Kias',5,1,'Season 3','Fotten'),
    ('WorldBranstar','Loz Kias',5,2,'Season 3','WorldBranstar'),
    ('Aby','Lyonide',5,4,'Season 3','Aby'),
    ('Fotten','Lyonide',5,1,'Season 3','Fotten'),
    ('Hazu','Lyonide',5,3,'Season 3','Hazu'),
    ('Jazair','Lyonide',5,4,'Season 3','Jazair'),
    ('WorldBranstar','Lyonide',5,2,'Season 3','WorldBranstar'),
    ('Petronixman','Miha Senju',5,3,'Season 3','Petronixman'),
    ('Vegasvat','Miha Senju',5,1,'Season 3','Vegasvat'),
    ('Horken','Momotehk',5,2,'Season 3','Horken'),
    ('Unicorn','Momotehk',5,3,'Season 3','Unicorn'),
    ('Vincent','Momotehk',5,1,'Season 3','Vincent'),
    ('MPhantasm','MonkeyKing',5,4,'Season 3','MPhantasm'),
    ('Baddy','Myloes',5,1,'Season 3','Baddy'),
    ('Ganondeurf','Neon',5,3,'Season 3','Ganondeurf'),
    ('Afflatus Misery','Ol[d]cadan',5,3,'Season 3','Afflatus Misery'),
    ('Zephyrion','Polosaty',5,1,'Season 3','Zephyrion'),
    ('Aelz','Rufus',10,6,'Season 3','Aelz'),
    ('TaokakaMeow','Sekirei',5,1,'Season 3','TaokakaMeow'),
    ('Domitto','Spirit410',5,1,'Season 3','Domitto'),
    ('Rufus','Spirit410',5,1,'Season 3','Rufus'),
    ('D3xus','Ssylus',10,2,'Season 3','D3xus'),
    ('Afflatus Misery','Tadlos',5,1,'Season 3','Afflatus Misery'),
    ('carriacou','Tadlos',5,0,'Season 3','carriacou'),
    ('Yaj-Ly','Tadlos',5,3,'Season 3','Yaj-Ly'),
    ('Blade of Flame','TaokakaMeow',5,2,'Season 3','Blade of Flame'),
    ('Darxy','TaokakaMeow',5,2,'Season 3','Darxy'),
    ('Stray','TaokakaMeow',5,4,'Season 3','Stray'),
    ('Greywall','TapiocaKing',5,1,'Season 3','Greywall'),
    ('Stray','TapiocaKing',5,0,'Season 3','Stray'),
    ('Kellerak','Unicorn',10,0,'Season 3','Kellerak'),
    ('MonkeyKing','Valhanya',5,4,'Season 3','MonkeyKing'),
    ('Loz Kias','VileMuffin',5,1,'Season 3','Loz Kias'),
    ('Valhanya','VileMuffin',5,4,'Season 3','Valhanya'),
    ('Ol[d]cadan','Vincent',5,2,'Season 3','Ol[d]cadan'),
    ('Stray','Vincent',5,3,'Season 3','Stray'),
    ('Spirit410','WorldBranstar',10,4,'Season 3','Spirit410'),
    ('Stray','Yaj-Ly',5,0,'Season 3','Stray'),
    ('Zephyrion','Yaj-Ly',5,2,'Season 3','Zephyrion'),
    ('Loz Kias','Zanaken',5,0,'Season 3','Loz Kias'),
    ('Darxy','Zollith',5,1,'Season 3','Darxy'),
    ('Taz','Zollith',5,4,'Season 3','Taz'),
    ('Zephyrion','Stray',5,2,'Season 2','Zephyrion'),
    ('D3xus','Aarpia',10,7,'Season 2','D3xus'),
    ('Danurai','Aby',5,4,'Season 2','Danurai'),
    ('Lyonide','Aby',5,3,'Season 2','Lyonide'),
    ('WorldBranstar','Aby',5,2,'Season 2','WorldBranstar'),
    ('Zollith','Aby',5,0,'Season 2','Zollith'),
    ('D3xus','Aelz',10,6,'Season 2','D3xus'),
    ('Baddy','Algernon',10,8,'Season 2','Baddy'),
    ('Loz Kias','Algernon',5,4,'Season 2','Loz Kias'),
    ('Domitto','Andyroo',10,3,'Season 2','Domitto'),
    ('Yin','Andyroo',10,7,'Season 2','Yin'),
    ('Andyroo','Baddy',10,8,'Season 2','Andyroo'),
    ('DarthSeppius','Baddy',10,9,'Season 2','DarthSeppius'),
    ('Sams','Baddy',10,5,'Season 2','Sams'),
    ('Sett','Baddy',10,8,'Season 2','Sett'),
    ('Habaduba','Blade of Flame',5,0,'Season 2','Habaduba'),
    ('HawkOfGP','carriacou',5,1,'Season 2','HawkOfGP'),
    ('Volty','carriacou',5,3,'Season 2','Volty'),
    ('Algernon','Ceiwen',5,2,'Season 2','Algernon'),
    ('Aarpia','D3xus',10,5,'Season 2','Aarpia'),
    ('Aelz','D3xus',10,5,'Season 2','Aelz'),
    ('Loz Kias','Doktai',5,4,'Season 2','Loz Kias'),
    ('Aelz','Domitto',10,5,'Season 2','Aelz'),
    ('D3xus','Domitto',5,1,'Season 2','D3xus'),
    ('Carnhulio','dopppa',5,3,'Season 2','Carnhulio'),
    ('Hazu','Dzing',5,1,'Season 2','Hazu'),
    ('Lyonide','Dzing',5,4,'Season 2','Lyonide'),
    ('Stray','ETS',5,4,'Season 2','Stray'),
    ('PanPan','Fergus',5,2,'Season 2','PanPan'),
    ('Polosaty','Finzy',5,2,'Season 2','Polosaty'),
    ('Sonder','Finzy',5,2,'Season 2','Sonder'),
    ('Doktai','Graveryl',5,3,'Season 2','Doktai'),
    ('Lyonide','Graveryl',5,4,'Season 2','Lyonide'),
    ('Baddy','Habaduba',10,3,'Season 2','Baddy'),
    ('Sett','Habaduba',5,3,'Season 2','Sett'),
    ('VileMuffin','Habaduba',5,1,'Season 2','VileMuffin'),
    ('Darxy','Hazu',5,0,'Season 2','Darxy'),
    ('Mozarus','Hazu',5,3,'Season 2','Mozarus'),
    ('Blade of Flame','Jazair',5,3,'Season 2','Blade of Flame'),
    ('Valhanya','Jazair',5,0,'Season 2','Valhanya'),
    ('Prizvel','Kreozot',5,3,'Season 2','Prizvel'),
    ('Habaduba','Loz Kias',5,3,'Season 2','Habaduba'),
    ('Habaduba','Lyonide',5,3,'Season 2','Habaduba'),
    ('Loz Kias','Lyonide',5,4,'Season 2','Loz Kias'),
    ('Ventras','Lyonide',5,4,'Season 2','Ventras'),
    ('Tadlos','Momotehk',5,0,'Season 2','Tadlos'),
    ('Algernon','MonkeyKing',5,1,'Season 2','Algernon'),
    ('VileMuffin','MonkeyKing',5,3,'Season 2','VileMuffin'),
    ('Zanaken','MonkeyKing',5,2,'Season 2','Zanaken'),
    ('MonkeyKing','Mozarus',5,2,'Season 2','MonkeyKing'),
    ('Ventras','Mozarus',5,1,'Season 2','Ventras'),
    ('ETS','nickvold',5,1,'Season 2','ETS'),
    ('Ol[d]cadan','nickvold',5,0,'Season 2','Ol[d]cadan'),
    ('Tadlos','nickvold',5,0,'Season 2','Tadlos'),
    ('The Arpeggiator','nickvold',5,0,'Season 2','The Arpeggiator'),
    ('carriacou','Ol[d]cadan',5,3,'Season 2','carriacou'),
    ('Doktai','PanPan',5,1,'Season 2','Doktai'),
    ('Yaj-Ly','PanPan',5,4,'Season 2','Yaj-Ly'),
    ('Finzy','Pikapi',5,4,'Season 2','Finzy'),
    ('Sonder','Pikapi',5,0,'Season 2','Sonder'),
    ('Stray','Polosaty',5,4,'Season 2','Stray'),
    ('ETS','Polosaty',5,2,'Season 2','ETS'),
    ('MonkeyKing','Polosaty',5,1,'Season 2','MonkeyKing'),
    ('Ennvill','Prizvel',5,4,'Season 2','Ennvill'),
    ('Graveryl','Rosa',5,1,'Season 2','Graveryl'),
    ('Pikapi','Ryuki',5,4,'Season 2','Pikapi'),
    ('Sonder','Ryuki',5,0,'Season 2','Sonder'),
    ('PanPan','Sekirei',5,2,'Season 2','PanPan'),
    ('Baddy','Sett',10,2,'Season 2','Baddy'),
    ('HolyCarp','Sett',5,1,'Season 2','HolyCarp'),
    ('Myloes','Sett',5,3,'Season 2','Myloes'),
    ('ZappySoyou','Sett',5,2,'Season 2','ZappySoyou'),
    ('Tadlos','SiloZen',5,0,'Season 2','Tadlos'),
    ('Stray','Sonder',5,3,'Season 2','Stray'),
    ('Polosaty','Sonder',5,1,'Season 2','Polosaty'),
    ('Aelz','Ssylus',10,9,'Season 2','Aelz'),
    ('Ryuki','Tadlos',5,3,'Season 2','Ryuki'),
    ('Ventras','TaokakaMeow',5,0,'Season 2','Ventras'),
    ('Polosaty','TapiocaKing',5,0,'Season 2','Polosaty'),
    ('SHARK','TapiocaKing',5,2,'Season 2','SHARK'),
    ('Tadlos','TapiocaKing',5,2,'Season 2','Tadlos'),
    ('Lyonide','Taz',5,3,'Season 2','Lyonide'),
    ('Aby','The Arpeggiator',5,3,'Season 2','Aby'),
    ('Mo[M]otehk','The Arpeggiator',5,0,'Season 2','Mo[M]otehk'),
    ('Graveryl','Unicorn',5,1,'Season 2','Graveryl'),
    ('Habaduba','Ventras',5,4,'Season 2','Habaduba'),
    ('VileMuffin','Ventras',5,4,'Season 2','VileMuffin'),
    ('Baddy','VileMuffin',5,4,'Season 2','Baddy'),
    ('Ceiwen','VileMuffin',5,1,'Season 2','Ceiwen'),
    ('Habaduba','VileMuffin',5,3,'Season 2','Habaduba'),
    ('Dzing','Vincent',5,4,'Season 2','Dzing'),
    ('Polosaty','Vincent',5,4,'Season 2','Polosaty'),
    ('PanPan','Volty',5,4,'Season 2','PanPan'),
    ('Ventras','Volty',5,0,'Season 2','Ventras'),
    ('Zephyrion','Volty',5,2,'Season 2','Zephyrion'),
    ('Guilu','Zanaken',5,3,'Season 2','Guilu'),
    ('Neon','ZappySoyou',5,2,'Season 2','Neon'),
    ('Rosa','Zaydan',5,0,'Season 2','Rosa'),
    ('Aby','Zephyrion',5,3,'Season 2','Aby'),
    ('Graveryl','Zephyrion',5,1,'Season 2','Graveryl'),
    ('Aarpia','ZER0',5,0,'Season 2','Aarpia'),
    ('Domitto','ZER0',5,4,'Season 2','Domitto'),
    ('MonkeyKing','@fon',5,2,'Season 1','MonkeyKing'),
    ('Aby','Stray',5,3,'Season 1','Aby'),
    ('carriacou','Stray',5,4,'Season 1','carriacou'),
    ('Doktai','Aby',5,1,'Season 1','Doktai'),
    ('D3xus','Aelz',10,1,'Season 1','D3xus'),
    ('Rufus','Aelz',5,3,'Season 1','Rufus'),
    ('Ssylus','Andyroo',10,3,'Season 1','Ssylus'),
    ('Ceiwen','Azizure',5,1,'Season 1','Ceiwen'),
    ('Hamidumi','Carnhulio',5,3,'Season 1','Hamidumi'),
    ('Valhanya','Carnhulio',5,0,'Season 1','Valhanya'),
    ('Fanlee Jr','Ceiwen',5,3,'Season 1','Fanlee Jr'),
    ('Prizvel','Cpt-GI',5,3,'Season 1','Prizvel'),
    ('Aarpia','DarthSeppius',10,4,'Season 1','Aarpia'),
    ('Domitto','DarthSeppius',10,9,'Season 1','Domitto'),
    ('Rufus','DarthSeppius',10,1,'Season 1','Rufus'),
    ('Jazair','Doktai',5,0,'Season 1','Jazair'),
    ('Sett','Doktai',5,4,'Season 1','Sett'),
    ('Spirit410','Domitto',10,6,'Season 1','Spirit410'),
    ('Ssylus','Domitto',5,3,'Season 1','Ssylus'),
    ('Algernon','dopppa',5,2,'Season 1','Algernon'),
    ('Azizure','dopppa',5,1,'Season 1','Azizure'),
    ('Polosaty','Ennvill',5,3,'Season 1','Polosaty'),
    ('Volty','Ennvill',5,4,'Season 1','Volty'),
    ('D3xus','Ganondeurf',10,5,'Season 1','D3xus'),
    ('MonkeyKing','Graveryl',5,3,'Season 1','MonkeyKing'),
    ('Baddy','Guilu',10,4,'Season 1','Baddy'),
    ('D3xus','Habaduba',10,3,'Season 1','D3xus'),
    ('Neon','Habaduba',10,8,'Season 1','Neon'),
    ('Sams','Habaduba',10,6,'Season 1','Sams'),
    ('dopppa','Hamidumi',5,2,'Season 1','dopppa'),
    ('Spear','Hamidumi',5,0,'Season 1','Spear'),
    ('Ventras','Hamidumi',5,0,'Season 1','Ventras'),
    ('Aarpia','HolyCarp',5,0,'Season 1','Aarpia'),
    ('TaokakaMeow','jc_near',5,3,'Season 1','TaokakaMeow'),
    ('SHARK','K.D.C.',5,1,'Season 1','SHARK'),
    ('Blade of Flame','Loz Kias',5,1,'Season 1','Blade of Flame'),
    ('Graveryl','Momotehk',5,1,'Season 1','Graveryl'),
    ('PanPan','Momotehk',5,4,'Season 1','PanPan'),
    ('Guilu','MonkeyKing',5,0,'Season 1','Guilu'),
    ('Baddy','Mozarus',5,1,'Season 1','Baddy'),
    ('Domitto','Neon',10,8,'Season 1','Domitto'),
    ('Stray','nickvold',5,0,'Season 1','Stray'),
    ('Vegasvat','Ol[d]cadan',5,3,'Season 1','Vegasvat'),
    ('Zephyrion','PanPan',5,0,'Season 1','Zephyrion'),
    ('Cpt-GI','Polosaty',5,1,'Season 1','Cpt-GI'),
    ('Ol[d]cadan','Polosaty',5,1,'Season 1','Ol[d]cadan'),
    ('Jazair','Prizvel',5,0,'Season 1','Jazair'),
    ('VileMuffin','Prizvel',5,0,'Season 1','VileMuffin'),
    ('Volty','Ryuki',5,1,'Season 1','Volty'),
    ('Yaj-Ly','Ryuki',5,1,'Season 1','Yaj-Ly'),
    ('Ceiwen','Sekirei',5,3,'Season 1','Ceiwen'),
    ('Taz','Sekirei',5,2,'Season 1','Taz'),
    ('Guilu','Sett',5,1,'Season 1','Guilu'),
    ('Stray','SHARK',5,0,'Season 1','Stray'),
    ('Zephyrion','SHARK',5,2,'Season 1','Zephyrion'),
    ('SHARK','Tadlos',5,4,'Season 1','SHARK'),
    ('Mozarus','Spear',5,3,'Season 1','Mozarus'),
    ('Ganondeurf','Spirit410',5,2,'Season 1','Ganondeurf'),
    ('ZappySoyou','Spirit410',5,3,'Season 1','ZappySoyou'),
    ('D3xus','Ssylus',5,3,'Season 1','D3xus'),
    ('Volty','TangAce',5,0,'Season 1','Volty'),
    ('Algernon','TaokakaMeow',5,3,'Season 1','Algernon'),
    ('VileMuffin','TaokakaMeow',5,4,'Season 1','VileMuffin'),
    ('Zaydan','TaokakaMeow',5,4,'Season 1','Zaydan'),
    ('Stray','TapiocaKing',5,1,'Season 1','Stray'),
    ('carriacou','TapiocaKing',5,0,'Season 1','carriacou'),
    ('nickvold','TapiocaKing',5,3,'Season 1','nickvold'),
    ('Azizure','Taz',5,4,'Season 1','Azizure'),
    ('Loz Kias','Taz',5,2,'Season 1','Loz Kias'),
    ('dopppa','terachi',5,2,'Season 1','dopppa'),
    ('MonkeyKing','terachi',5,1,'Season 1','MonkeyKing'),
    ('Baddy','Valhanya',5,4,'Season 1','Baddy'),
    ('Sett','Valhanya',5,2,'Season 1','Sett'),
    ('Carnhulio','Vegasvat',5,4,'Season 1','Carnhulio'),
    ('MPhantasm','Vegasvat',5,1,'Season 1','MPhantasm'),
    ('Prizvel','Vegasvat',5,1,'Season 1','Prizvel'),
    ('VileMuffin','Ventras',5,4,'Season 1','VileMuffin'),
    ('Sett','VileMuffin',5,2,'Season 1','Sett'),
    ('Zanaken','Volty',5,1,'Season 1','Zanaken'),
    ('Ganondeurf','Yin',10,7,'Season 1','Ganondeurf'),
    ('PanPan','Yuusha42',5,4,'Season 1','PanPan'),
    ('Aelz','ZappySoyou',5,1,'Season 1','Aelz'),
    ('Fotten','Zephyrion',5,0,'Season 1','Fotten'),
    ('Baddy','Zollith',5,3,'Season 1','Baddy'),
    ('Hazu','Zollith',5,0,'Season 1','Hazu');

  -- Insert unique events
  INSERT INTO events(title, event_date)
  SELECT DISTINCT event, NOW()
    FROM seeddata
  WHERE 
    NOT EXISTS(
      SELECT 1
      FROM events AS E
      WHERE E.title = seeddata.event
    )
  ORDER BY event ACC;

  -- Insert unique players
  INSERT INTO players(name)
  SELECT DISTINCT name
    FROM (
      SELECT player1 as name FROM seeddata
      UNION SELECT player2 FROM seeddata
    ) AS T
  WHERE 
    NOT EXISTS(
      SELECT 1
      FROM players AS P
      WHERE P.name = T.name
    );

  -- Remove previous seed data
  DELETE FROM matches WHERE is_fake_data = true;

  -- Insert match data
  INSERT INTO matches(
    player1_id, player1_score,
    player2_id, player2_score, 
    winner_id, event_id, is_fake_data
  )
  SELECT
    P1.id, S.player1score,
    P2.id, S.player2score,
    W.id,
    E.id,
    true
  FROM seeddata as S
  INNER JOIN players AS P1 ON P1.name = S.player1
  INNER JOIN players AS P2 ON P2.name = S.player2
  INNER JOIN players AS W ON W.name = S.winner
  INNER JOIN events AS E ON E.title = S.event;

  DROP TABLE seeddata;
END $$;
